---
# NTP server
# http://www.ntp.org/
# http://www.pool.ntp.org/en/
- debug: msg="NTP Server "


# install
- name: ntp installed
  apt: name=ntp state=present
  become: yes
  tags: [ntp]


# enabled on boot
- name: ntp enabled on boot
  service: name=ntp enabled=yes
  become: yes
  tags: [ntp]


# config file - Servers
- name: ntpd SERVER conf
  template:
    src: ntp_server.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
  become: yes
  notify: ntp_restart
  tags: [ntp]


# started
- name: ntp started
  service: name=ntp state=started
  become: yes
  tags: [ntp]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
  become: yes
  tags: [ntp]
