---


- debug: msg="install jenkins"
  tags: [jenkins]


- name: copy jenkins key
  copy:
    src: jenkins_io.key
    dest: /opt/cluster/data/jenkins_io.key
    mode: 0644
  register: jekinskey
  tags: [jenkins]


- name: Add jenkins apt key
  apt_key:
    file: /opt/cluster/data/jenkins_io.key
    state: present
  become: yes
  tags: [jenkins]


- name: setup jenkins apt repo
  copy:
    content: 'deb http://pkg.jenkins.io/debian-stable binary/'
    dest: /etc/apt/sources.list.d/jenkins.list
  become: yes
  tags: [jenkins]


- name: update apt cache
  apt: update_cache=yes
  become: yes
  retries: 2
  check_mode: no
  tags: [jenkins]


- name: install jenkins packages
  apt: name={{ item }} state=present
  with_items:
       - jenkins
  become: yes
  tags: [jenkins]


- name: jenkins.service enabled on boot
  service: name=jenkins.service enabled=yes
  become: yes
  tags: [jenkins]


- name: jenkins.service started
  service: name=jenkins.service state=started
  become: yes
  tags: [jenkins]


# wget localhost:8080/jnlpJars/jenkins-cli.jar
