---
galaxy_info:
  role_name: dhcp-server
  author: crgm
  description: A DHCP server for the cluster
  company: crgm inc
  license: license (no)
  min_ansible_version: 2.8
  platforms:
  - name: Raspbian
    versions:
      - stretch
dependencies:
  - role: base-system
  - role: dns-server
