---
# Redis server - https://redis.io/
- debug: msg="Redis server role "


- name: install redis
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - redis-tools
       - redis-server
  become: yes
  tags: [redis]


- name: redis-server is started and enabled
  service:
    name: redis-server
    state: started
    enabled: yes
  become: yes
  tags: [redis]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [redis]
