---
# Redis server - https://redis.io/
- debug: msg="Redis server role "


- name: install redis
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - redis-tools
       - redis-server
  become: yes
  tags: [redis]


- name: redis-server is started and enabled
  service:
    name: redis-server
    state: started
    enabled: yes
  become: yes
  tags: [redis]


- name: install python redis module
  pip:
    name: redis
  become: yes
  tags: [redis]


- name: get redis server info
  command: redis-cli info server
  register: redis_server_info
  changed_when: false


- name: check redis server ok
  assert:
    that:
      - "'process_id' in redis_server_info.stdout"


- name: Configure local redis to have 500 max clients
  redis:
    command: config
    name: maxclients
    value: 500
  tags: [redis]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [redis]
