---
# Log file for cluster events
- debug: msg="rpilog "


- name: check for ssl cert
  stat:
    path: /var/log/rpicluster.log
  register: rpiclustlog_exist
  tags: [rpilog]


# create rpicluster.log
- name: create rpicluster log
  file:
    path: /var/log/rpicluster.log
    state: touch
    owner: root
    group: adm
    mode: 0664
  become: true
  when: rpiclustlog_exist.stat.exists == false
  register: rpiclustlog_created
  tags: [rpilog]


# copy test script - will check this role is working after run
- name: copy testing script
  copy:
    src: test-rpilog.sh
    dest: /opt/cluster/bin/test-rpilog.sh
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  register: rpiclustlog_test_sh
  tags: [rpilog]


  # first line rpicluster.log
- name: log test
  shell: echo "first log line!" > /var/log/rpicluster.log
  when: rpiclustlog_created.changed == True
  become: true
  tags: [rpilog]


# Logrotate scripts
- name: logroate.d for rpicluster log
  template:
    src: rpilogro.j2
    dest: /etc/logrotate.d/rpilog
    mode: 0644
    owner: root
    group: root
  become: true
  notify: syslog-restart
  tags: [rpilog]


# rsyslog rpicluster filter
- name: rsyslog filters for rpicluster
  copy:
    src: 22-rpicluster.conf
    dest: /etc/rsyslog.d/22-rpicluster.conf
    mode: 0644
    owner: root
    group: root
  become: true
  notify: syslog-restart
  tags: [rpilog]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [rpilog]
