" vim config
" {{ ansible_managed }}

:set smartindent
:syntax on

:set nobackup                   " no backup files
:set backupdir=~/tmp            " backup files here to be sure
:set dir=~/tmp                  " save vim temp files here


" disable autopaste
" from https://coderwall.com/p/if9mda/automatically-set-paste-mode-in-vim-when-pasting-in-insert-mode
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"

inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()

function! XTermPasteBegin()
  set pastetoggle=<Esc>[201~
  set paste
  return ""
endfunction


" status line
set statusline=%t               " tail of the filename
set statusline+=%m              " modified flag
set statusline+=%r              " read only flag
set statusline+=%h              " help file flag
set statusline+=%w
set statusline+=\ [%{strlen(&fenc)?&fenc:'enc'}] " file encoding
set statusline+=\ [%{&ff}]      " file format
set statusline+=\ %y            " filetype
set statusline+=\ [ASCII=\%03.3b]
set statusline+=\ [HEX=\%02.2B]
set statusline+=\ [Line\ %l\/%L]        " cursor line/total lines
hi StatusLine ctermfg=Black ctermbg=White
au InsertEnter * hi StatusLine ctermbg=DarkBlue
au InsertLeave * hi StatusLine ctermfg=Black ctermbg=White
set laststatus=2
