---
# NFS Server (LanServices - Misc)
- debug: msg="NFS Server role "
  tags: [nfs]


# packages
- name: install NFS programs
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-server
    - nfs-kernel-server
    - nfs-common
    - rpcbind
  become: true
  retries: 2
  tags: [nfs]


# folder to share
- name: create /srv/nfs_share/
  file:
    path: /srv/nfs_share/
    state: directory
    mode: 0775
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  tags: [nfs]


# copy test file
- name: copy test_file.txt to srv
  template:
    src: test_file.j2
    dest: /srv/nfs_share/test_file.txt
    mode: 0644
    owner: root
    group: root
  changed_when: False
  become: true
  tags: [nfs]


# service: nfs-idmapd
- name: nfs-idmapd enabled and started on boot
  service:
    name: nfs-idmapd
    enabled: true
    state: started
  become: true
  tags: [nfs]


# service: rpcbind
- name: rpcbind.service enabled and started on boot
  service:
    name: rpcbind.service
    state: started
    enabled: true
  become: true
  tags: [nfs]


# service: nfs-kernel-server
- name: nfs-kernel-server.service enabled and started on boot
  service:
    name: nfs-kernel-server.service
    state: started
    enabled: true
  become: true
  tags: [nfs]


# copy export file
- name: copy exports file
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  register: nfs_exports_file
  tags: [nfs]


# update exports
- name: run exportfs
  become: true
  action: command exportfs -a
  when: nfs_exports_file.changed
  tags: [nfs]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [nfs]
