---
# handlers for group-lanservices


- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes
  become: yes


- name: restart-rpilansrv
  service:
    name: rpi-lanservices.service
    state: restarted
  become: yes


# static arp
- name: static-arp-ethers
  command: /usr/sbin/arp -f /etc/ethers
  become: yes


- name: reload-rsyslog
  service:
    name: rsyslog.service
    state: restarted
  become: yes