---
- debug: msg="altering /etc/hosts "


# /etc/hosts file 
# add all hosts we have in our ansible inventory
- name: etc hosts file
  template:
    src: etc-hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [hostsfile]


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible hostsfile role ran
  changed_when: False
  tags: [hostsfile]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [hostsfile]
