---
- debug: msg="altering /etc/hosts "


# hosts file
- name: etc hosts file
  template:
    src: etc-hosts.j2
    dest: /etc/hosts
    wner: root
    group: root
    mode: 0644
  become: yes
  tags: [hostsfile]


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible hostsfile role ran
  changed_when: False
  tags: [hostsfile]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [hostsfile]
