---
# Deployer

- name: Deployer
  hosts: deploy
  gather_facts: True
  roles:
    - ansible-pre-role
    - userac
    - base-system
    - rpilog
    - ssh
    - haveged
    - ntp-server
    - redis
    - nodejs
    - deployer
    - ansible-post-role

- name: Deployer VagrantVM
  hosts: stretch
  gather_facts: True
  roles:
    - docker
    - host-vagrantvm

- name: Deployer Psi
  hosts: pis
  gather_facts: True
  roles:
    - host-psi
