---
# Compute webapp hosting Playbook

- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  roles:
    - ansible-pre-role

- name: Copute nodes base
  hosts: compute
  gather_facts: false
  roles:
    - base-system
    - rpilog

- name: Docker engine
  hosts: docker
  gather_facts: false
  roles:
    - docker

# hosts: delta
#- name: Docker swarm
#  hosts: docker_swarminit
#  gather_facts: false
#  roles:
#    - docker-swarm

- name: webapp frontend
  hosts: frontend
  gather_facts: false
  roles:
    - nginx
    - haproxy
    - keepalived

- name: gather facts on nodes
  hosts: all
  gather_facts: True
  roles:
    - ansible-post-role
