---
# A playbook to reboot a node, and then test the system went down

- debug: msg="rebooting {{ inventory_hostname }} "


# log
- name: output to rpicluster log
  command: logger -t rpicluster maintenance role is rebooting host
  changed_when: False
  tags: [maintenance]


# reboot host
- name: reboot host
  shell: sleep 2 && reboot now
  become: yes
  retries: 2
  async: 45
  poll: 0
  ignore_errors: true
  tags: [maintenance]


- name: wait for host to restart
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 22
    state: started
    delay: 60
    timeout: 240
  with_items: '{{ play_hosts }}'
  connection: local
  tags: [maintenance]


- name: test host has rebooted
  script: check_rebooted.sh
  tags: [maintenance]
  changed_when: False
  register: rpi_my_uptime_check


# get uptime
- name: uptime
  command: uptime
  register: rpi_my_uptime
  changed_when: False
  tags: [maintenance]


# show uptime
- debug: msg="uptime {{ rpi_my_uptime }} "
  tags: [maintenance]


# log
- name: output to rpicluster log
  command: logger -t rpicluster maintenance role - host is up
  changed_when: False
  tags: [maintenance]
