---
- debug: msg="rebooting {{ inventory_hostname }} "


# log
- name: output to rpicluster log
  shell: logger -t rpicluster maintenance role is rebooting host
  changed_when: False
  tags: [maintenance]


# reboot host
- name: reboot host
  shell: sleep 2 && reboot now
  become: yes
  async: 30
  poll: 0
  ignore_errors: true
  tags: [maintenance]


# wait for host
- name: wait for host to restart
  wait_for:
    host: '{{ ansible_default_ipv4.address }}'
    port: 22
    state: started
    delay: 40
    timeout: 240
  with_items: '{{ play_hosts }}'
  connection: local
  tags: [maintenance]


# longer pause between lanservices
- name: wait for lanservices
  pause:
    seconds: 60
  when: "'lanservices' in group_names"
  tags: [maintenance]


# get uptime
- name: uptime
  shell: uptime
  tags: [maintenance]
  register: rpi_my_uptime
  changed_when: False


# show upttime
- debug: msg="uptime {{ rpi_my_uptime }} "
  tags: [maintenance]


# log
- name: output to rpicluster log
  shell: logger -t rpicluster maintenance role - host is up
  changed_when: False
  tags: [maintenance]
