---
- debug: msg="VagrantVM Hugo install "
# https://gohugo.io/


# src dir
- name: create /opt/cluster/mysrc/hugo/
  file: path=/opt/cluster/mysrc/hugo/ state=directory mode=0755


# check .deb
- name: check hugo deb file dowloaded
  stat: path=/opt/cluster/mysrc/hugo/{{ hugo_64bit_deb }}
  register: hugodeb


# check user local bin
- name: check hugo bin
  stat: path=/usr/local/bin/hugo
  register: hugolocalbin


# hugo download
- name: download hugo .deb
  get_url:
    url: "{{ hugo_64bit_url }}"
    dest: /opt/cluster/mysrc/hugo/
    checksum: sha256:{{ hugo_64bit_sha }}
  register: hugodebdl
  retries: 3
  delay: 12
  when: hugodeb.stat.exists == False


# hugo install
- name: Install a hugo.deb package
  shell: dpkg -i /opt/cluster/mysrc/hugo/{{ hugo_64bit_deb }}
  become: yes
  when: hugolocalbin.stat.exists == False
