---
# install Rust
# https://www.rust-lang.org/en-US/other-installers.html


# check bin exists
- name: check rust installer
  stat: path=/opt/cluster/mysrc/rust/rust-1.23.0-x86_64-unknown-linux-gnu/install.sh
  register: rustinstaller
  tags: [rust]


# src dir
- name: make /opt/cluster/mysrc/rust/
  file: path=/opt/cluster/mysrc/rust/ state=directory mode=0775


# check rust .tar.gz
- name: check rust tar gz
  stat: path=/opt/cluster/mysrc/rust/rust-1.23.0-x86_64-unknown-linux-gnu.tar.gz
  register: golangbintargz
  tags: [rust]


# download rust
- name: download rust
  get_url:
    url: https://static.rust-lang.org/dist/rust-1.23.0-x86_64-unknown-linux-gnu.tar.gz
    dest: /opt/cluster/mysrc/rust/
    checksum: sha256:9a34b23a82d7f3c91637e10ceefb424539dcfa327c2dcd292ff10c047b1fdc7e
  when: golangbintargz.stat.exists == False
  register: rustbintargzdownload
  tags: [rust]


# unarchive rust
- name: unarchive rust
  unarchive:
    src: /opt/cluster/mysrc/rust/rust-1.23.0-x86_64-unknown-linux-gnu.tar.gz
    dest: /opt/cluster/mysrc/rust/
    mode: 0755
    remote_src: yes
  when: rustinstaller.stat.exists == False
  tags: [rust]
