---
# busybox httpd in chroot
# https://git.busybox.net/busybox/tree/networking/httpd.c
- debug: msg="busybox httpd chroot "


# source folder
- name: make temp source folder
  file:
    path: "{{ bbhttpd_src_tmp }}"
    state: directory
    mode: 0755
    recurse: false
  tags: [bbhttpd]


# copy files
- name: copy install files
  copy:
    src: "{{ item.src }}"
    dest: "{{ bbhttpd_src_tmp }}/"
    mode: 0644
    force: false
  with_items: "{{ files }}"
  tags: [bbhttpd]


# run installer script
- name: install busybox chroot
  script: "chroot_bb.sh"
  args:
    creates: /opt/chroot_bb/etc/tested
    chdir: "{{ bbhttpd_src_tmp }}"
  become: true
  when:
    - "rpi_bb_httpd_enabled == true"
  tags:
    - bbhttpd
    - skip_ansible_lint


# index.html
- name: index.html template
  template:
    src: ansible-index.j2
    dest: /opt/chroot_bb/www/index.html
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  become: true
  changed_when: false
  when: rpi_bb_httpd_enabled == true
  tags: [bbhttpd]


# stop if diabled flag
- name: bbhttpd disabled
  service:
    name: bbhttpd
    state: stopped
  become: true
  when: rpi_bb_httpd_enabled == false
  tags: [bbhttpd]


# test website deployed - Get page
- name: get index.html content
  uri:
    url: http://127.0.0.1:1080/index.html
    return_content: true
  register: bbhttpd_index
  ignore_errors: true
  tags: [bbhttpd]


# check page
- name: test bbhttpd index.html content
  fail:
  when: "'R-Pi BB httpd' not in bbhttpd_index.content"
  ignore_errors: true
  tags:
    - bbhttpd
    - skip_ansible_lint


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [bbhttpd]
