# Common Vars for all hosts

# create folders (on every R-Pi)
common_dir: [
  { dir: '/opt/cluster/', mode: '0770', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/data/', mode: '0700', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/bin/', mode: '0755', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/etc/ansible/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/etc/ansible/facts.d/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/home/{{ ansible_user_id }}/tmp/', mode: '0750', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/root/bin/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/root/tmp/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/mnt/usbkey/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/mnt/sshfs/', mode: '0755', owner: 'root', group: 'root' }
]

# copy files
dotfiles: [
  {src: 'files/dotfiles/screenrc', dest: '~/.screenrc'},
  {src: 'files/dotfiles/vimrc', dest: '~/.vimrc'}
]

# copy ./files/bash-script/x to ~/bin/ on each host
binfile: [
  {file: 'fix_apt.sh'},
  {file: 'free_memcache.sh'},
  {file: 'led-blink.sh'},
  {file: 'disable-swap.sh'},
  {file: 'speedtest_100mbit.sh'},
  {file: 'check-syshealth.sh'}
]

# remove these packages on all nodes
package_remove: [
  {rmapt: 'avahi-daemon'},
  {rmapt: 'triggerhappy'},
]


# net.core.rmem_max
sysctl_cnf_rmem_max: "16777216"

# net.core.wmem_max
sysctl_cnf_wmem_max: "4194304"

# disable Ipv6 (0 = no, 1 = yes)
sysctl_cnf_ipv6_off: "1"
