---
# bind config files


- name: /etc/default/bind9
  template:
    src: etc/default/bind.j2
    dest: /etc/default/bind9
    owner: root
    group: root
    mode: 0644
  become: true
  notify: bind-restart
  tags: [bind]


- name: bind conf local
  template:
    src: etc/bind/named_conf_local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: 0644
  become: true
  notify: bind-restart
  tags: [bind]


- name: named conf options
  template:
    src: etc/bind/named_conf_options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: 0644
  become: true
  notify: bind-restart
  tags: [bind]


- name: named conf default zones
  template:
    src: etc/bind/named_conf_default_zones.j2
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: root
    mode: 0644
  become: true
  notify: bind-restart
  tags: [bind]


- name: Bind keys
  template:
    src: etc/bind/bind_keys.j2
    dest: /etc/bind/bind.keys
    owner: root
    group: root
    mode: 0644
    backup: false
  become: true
  notify: bind-restart
  tags: [bind]


- import_tasks: master-zone.yml
  tags:
    - bind
    - alpha


- name: check named conf
  command: /usr/sbin/named-checkconf /etc/bind/named.conf
  become: true
  changed_when: False
  tags: [bind]
