---
# Named DNS server - run by admin nodes Alpha and Beta
- debug: msg="DNS status {{ rpi_dnsd_status }} "
  tags: [bind]


- debug: msg="Custom domain is {{ rpi_cust_domain }}.{{ rpi_cust_tld }} "
  tags: [bind]


- name: install DNS server packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - bind9
       - bind9utils
  become: yes
  retries: 1
  notify: bind-restart
  tags: [bind]


# folder structure
- name: Create bind folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ bind_dir }}"
  become: yes
  tags: [bind]


# in /etc/bind/zones/ create "master" OR "slave"
- name: zones folder for dns status
  file:
    path: /etc/bind/zones/{{ rpi_dnsd_status }}/
    state: directory
    owner: bind
    group: bind
    mode: 0775
  become: yes
  tags: [bind]


#-------------------------------------------------------------------------------
# Local config


- name: /etc/default/bind9
  template:
    src: bind_default.j2
    dest: /etc/default/bind9
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: bind-restart
  tags: [bind]


- name: bind conf local
  template:
    src: named_conf_local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: bind-restart
  tags: [bind]


- name: named conf options
  template:
    src: named_conf_options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: bind-restart
  tags: [bind]


- name: named conf default zones
  template:
    src: named_conf_default_zones.j2
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: bind-restart
  tags: [bind]


- name: bind conf consul
  template:
   src: consul_conf.j2
   dest: /etc/bind/consul.conf
   owner: root
   group: root
   mode: 0644
  become: yes
  notify: bind-restart
  tags: [bind]


- name: Bind keys
  template:
   src: bind_keys.j2
   dest: /etc/bind/bind.keys
   owner: root
   group: root
   mode: 0644
   backup: yes
  become: yes
  notify: bind-restart
  tags: [bind]


- import_tasks: master-zone.yml
  tags: [bind]


- name: rpi reverse zone db
  template:
    src: db_reverse.j2
    dest: /etc/bind/zones/{{ rpi_dnsd_status }}/reverse-{{ rpi_dnsd_status }}.db
    owner: root
    group: bind
    mode: 0664
    backup: yes
  become: yes
  notify: bind-restart
  tags:
    - bind
    - dns-server-zone


- name: check named conf
  shell: /usr/sbin/named-checkconf /etc/bind/named.conf
  become: yes
  changed_when: False
  tags: [bind]


#-------------------------------------------------------------------------------

# enabled on boot and running (if flagged on)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: yes
    state: started
  become: yes
  when: rpi_dnsd_enabled  == true
  tags: [bind]


# not on boot (if flagged off)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: no
    state: stopped
  become: yes
  when: rpi_dnsd_enabled == false
  tags: [bind]

#-------------------------------------------------------------------------------


# /etc/resolv.conf
- name: etc resolv conf
  template:
    src: resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: bind
    mode: 0664
  become: yes
  tags: [bind]


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible dns-server role ran as {{ rpi_dnsd_status }}
  tags: [bind]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [bind]
