---
# Named DNS server - run by admin nodes Alpha and Beta
- debug: msg="DNS status {{ rpi_dnsd_status }} "
  tags: [bind]

# to show root servers:
#
# dig +bufsize=1200 +norec NS . @a.root-servers.net > named.ca

- name: check these keys exist
  assert:
    that:
    - rpi_dnsd_status is defined
    - rpi_dnsd_notify is defined
    - rpi_cust_domain is defined
    - rpi_cust_tld is defined


- debug: msg="Custom domain is {{ rpi_cust_domain }}.{{ rpi_cust_tld }} "
  tags: [bind]


- name: install DNS server packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - bind9
    - bind9utils
  become: true
  retries: 1
  notify: bind-restart
  tags: [bind]


# folder structure
- name: Create bind folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: false
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ bind_dir }}"
  become: true
  tags: [bind]


# in /etc/bind/zones/ create "master" OR "secondary"
- name: zones folder for dns status
  file:
    path: /etc/bind/zones/{{ rpi_dnsd_status }}/
    state: directory
    owner: bind
    group: bind
    mode: 0775
  become: true
  tags: [bind]

#-------------------------------------------------------------------------------
# Local config

- import_tasks: local-config.yml
  tags: [bind]

#-------------------------------------------------------------------------------

# enabled on boot and running (if flagged on)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: true
    state: started
  become: true
  when:
    - rpi_dnsd_enabled == true
  tags: [bind]


# not on boot (if flagged off)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: no
    state: stopped
  become: true
  when:
    - rpi_dnsd_enabled == false
  tags: [bind]

#-------------------------------------------------------------------------------


# /etc/resolv.conf
- name: etc resolv conf
  template:
    src: resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: bind
    mode: 0664
  become: true
  tags: [bind]
  when:
    - rpi_dnsd_enabled == true


- name: bats file for tests
  template:
    src: dns_tests_bats.j2
    dest: /opt/cluster/bin/dns_tests_bats.sh
    owner: root
    group: root
    mode: 0755
  become: true


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible dns-server role ran as {{ rpi_dnsd_status }}
  tags: [bind]
  changed_when: False
  when:
    - rpi_dnsd_enabled == true


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [bind]
  when:
    - rpi_dnsd_enabled == true
