---
# Named DNS server - run by admin nodes Alpha and Beta
- debug: msg="DNS status {{ rpi_dnsd_status }} "
  tags: [bind]


- debug: msg="Custom domain is {{ rpi_cust_domain }}.{{ rpi_cust_tld }} "
  tags: [bind]


- name: install DNS server packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - bind9
       - bind9utils
  become: yes
  retries: 1
  notify: bind-restart
  tags: [bind]
  when:
    - rpi_dnsd_enabled == true
    - "'lanservices' in group_names"


# folder structure
- name: Create bind folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ bind_dir }}"
  become: yes
  tags: [bind]
  when:
    - "'lanservices' in group_names"

# in /etc/bind/zones/ create "master" OR "secondary"
- name: zones folder for dns status
  file:
    path: /etc/bind/zones/{{ rpi_dnsd_status }}/
    state: directory
    owner: bind
    group: bind
    mode: 0775
  become: yes
  tags: [bind]
  when:
    - "'lanservices' in group_names"

#-------------------------------------------------------------------------------
# Local config

- import_tasks: local-config.yml
  tags: [bind]
  when:
    - "'lanservices' in group_names"


#-------------------------------------------------------------------------------

# enabled on boot and running (if flagged on)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: yes
    state: started
  become: yes
  when:
    - rpi_dnsd_enabled == true
    - "'lanservices' in group_names"
  tags: [bind]


# not on boot (if flagged off)
- name: bind9 enabled on boot
  service:
    name: bind9
    enabled: no
    state: stopped
  become: yes
  when:
    - rpi_dnsd_enabled == true
    - "'lanservices' in group_names"
  tags: [bind]

#-------------------------------------------------------------------------------


# /etc/resolv.conf
- name: etc resolv conf
  template:
    src: resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: bind
    mode: 0664
  become: yes
  tags: [bind]
  when:
    - rpi_dnsd_enabled == true


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible dns-server role ran as {{ rpi_dnsd_status }}
  tags: [bind]
  changed_when: False
  when:
    - rpi_dnsd_enabled == true


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [bind]
  when:
    - rpi_dnsd_enabled == true
    - "'lanservices' in group_names"
