---
# Raspberry Pi cluster Zone file for Master


- name: rpi dns zone file
  template: src=db_rpi.j2 dest=/etc/bind/zones/{{ rpi_dnsd_status }}/rpi-{{ rpi_dnsd_status }}.db owner=root group=bind mode=0664
  become: yes
  notify: bind-restart
  when: "'alpha' in inventory_hostname"
  tags: [alpha]


- name: test rpi zone db
  shell: /usr/sbin/named-checkzone {{ rpi_cust_domain }}.{{ rpi_cust_tld }} /etc/bind/zones/{{ rpi_dnsd_status }}/rpi-master.db
  changed_when: False
  when: "'alpha' in inventory_hostname"
  tags: [alpha]
