---
# Raspberry Pi cluster Zone file for Master


- name: rpi dns zone file
  template:
    src: db_rpi.j2
    dest: /etc/bind/zones/{{ rpi_dnsd_status }}/{{ rpi_cust_tld }}.db
    owner: bind
    group: bind
    mode: 0664
  become: yes
  notify: bind-restart
  when:
    - rpi_dnsd_status == "master"

#- name: test rpi zone db
- name: check and dump db_rpi.db
  shell: /usr/sbin/named-compilezone -F text -o /opt/cluster/lanservice/zones.txt {{ rpi_cust_domain }}.{{ rpi_cust_tld }} /etc/bind/zones/{{ rpi_dnsd_status }}/{{ rpi_cust_tld }}.db
  changed_when: False
  when:
    - rpi_dnsd_status == "master"
