---
# Run on the Deployers (The R-Pi "psi" & AdminVM)

- debug: msg="deployer role "


# ssh config
- name: .ssh/config template
  template:
    src: ssh-config.j2
    dest: ~/.ssh/config
    mode: 0640
  tags: [deployer]



# Download src/pacakges etc
- import_tasks: dl_packages.yml
  tags: [deployer]


# yarn
- import_tasks: yarn.yml
  tags: [deployer,yarn]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [deployer]
