CREATE TABLE `rpies` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`date` TIMESTAMP NOT NULL AUTO_INCREMENT UNIQUE,
	`hostname` varchar(20) NOT NULL AUTO_INCREMENT UNIQUE,
	`ip` varchar(20) NOT NULL AUTO_INCREMENT UNIQUE,
	`mac` varchar(20) NOT NULL AUTO_INCREMENT UNIQUE,
	`group` varchar(20) NOT NULL AUTO_INCREMENT UNIQUE,
	PRIMARY KEY (`id`)
);
