

docker_dir: [
  { dir: '/opt/cluster/docker/', mode: '0770', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/docker/compose/', mode: '0770', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/docker/scripts/', mode: '0770', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/docker/volumes/', mode: '0770', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" }
]

docker_script: [
  {file: 'rm_all_images.sh'},
  {file: 'remove_docker.sh'}
]

