---
# Users public and private SSH keys
- debug: msg="ssh (keys) "


# check for ~/.ssh/id_rsa
- name: check for users id_rsa
  stat: path="~/.ssh/id_rsa"
  register: sshprivkeyexists


# generate ssh key for current user if missing
- name: Generate id_rsa for this user if missing
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: ~/.ssh/id_rsa
  tags: [common,commonssh,ssh]
  when:
    - sshprivkeyexists.stat.exists == false
  register: gen_ansible_user_ssh


- name: check ssh backup
  stat: path="/opt/cluster/data/{{ inventory_hostname }}_ssh_bu.tgz"
  register: sshpribackup
  become: true


# backup generated key and ~/.ssh/
- name: backup user ssh dir on remote host
  archive:
    path: /home/{{ ansible_user_id }}/.ssh/
    dest: "/home/pi/.{{ inventory_hostname }}_ssh_bu.tgz"
    mode: 0440
  become: true
  when: sshpribackup.stat.exists == false


# Saves to /opt/cluster/backup/<host>/home/<user>/.ssh/
- name: fetch the ssh public key
  fetch:
    src: ~/.ssh/id_rsa.pub
    dest: /opt/cluster/backup


- name: fetch the ssh PRIVATE key
  fetch:
    src: ~/.ssh/id_rsa
    dest: /opt/cluster/backup
