---
- debug: msg="userac role "


# To update password hashs in ansible dir run:
# source ./env/bin/activate
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"


# create group "sshusers" for /etc/ssh/sshd_config "AllowGroups"
- name: add sshusers group
  group:
    name: sshusers
    state: present
  become: true
  tags: userac


# check user is defined
- name: check rpi_clust_user not empty
  assert:
    that:
      - rpi_clust_user != ''



# Create {{ rpi_clust_user }} user on all hosts
- name: create rpi_clust_user
  user:
    name: "{{ rpi_clust_user }}"
    groups: sshusers,sudo,staff,backup
    append: true
    createhome: true
    home: "/home/{{ rpi_clust_user }}"
  become: true
  tags: userac


# fix home dir defaults of drwxr-xr-x for {{ rpi_clust_user }} :(
- name: fix homedir perms
  file:
    path: "/home/{{ rpi_clust_user }}"
    state: directory
    mode: 0700
  become: true
  tags: userac


# PASSWORDS for system accounts!
- name: update passwords
  user:
    name: "{{ item.user }}"
    update_password: always
    password: "{{ item.hash }}"
  with_items: "{{ vault_user_pw }}"
  become: true
  no_log: True
  tags: userac


# ssh keys
- import_tasks: keys.yml
  tags: userac


#- name: Remove default nopasswd sudo rule
#  file:
#    path: /etc/sudoers.d/010_pi-nopasswd
#    state: absent
#  become: true
#  tags: userac