---
# system users
- debug: msg="user accounts "

# to update in ansible dir run:
#
# source ./env/bin/activate
# python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt(getpass.getpass())"


# create group "sshusers" for /etc/ssh/sshd_config "AllowGroups"
- name: add sshusers group
  group:
    name: sshusers
    state: present
  become: yes


# Create {{ rpi_clust_user }} user on all hosts
- name: create rpi_clust_user
  user:
    name: "{{ rpi_clust_user }}"
    groups: sshusers,sudo,staff,backup
    append: yes
    createhome: yes
    home: "/home/{{ rpi_clust_user }}"
  become: yes


# fix home dir defaults of drwxr-xr-x for {{ rpi_clust_user }} :(
- name: fix homedir perms
  file: path="/home/{{ rpi_clust_user }}" state=directory mode=0700
  become: yes


# PASSWORDS for system accounts!
- name: update passwords
  user:
    name: "{{ item.user }}"
    update_password: always
    password: "{{ item.hash }}"
  with_items: "{{ vault_user_pw }}"
  become: yes


# ssh keys
- import_tasks: keys.yml
