---


- name: remove default passwordless sudo conf file
  file:
    state: absent
    path: "/etc/sudoers.d/010_pi-nopasswd"
  become: yes

# this file contains the line:
#
# pi ALL=(ALL) NOPASSWD: ALL
