---
- debug: msg="mpich role"
  tags: [mpich]


# install packages
- name: mpich packages needed
  apt:
    name: "{{ item }}"
    state: present
  loop:
      - mpich
      - mpich-doc
      - gfortran
  become: true
  retries: 2
  tags: [mpich]


- import_tasks: mpi-test-code.yml


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [mpich]
