---
- debug: msg="mpich role"
  tags: [mpich]


# install packages
- name: mpich packages needed
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - mpich
       - mpich-doc
       - gfortran
  become: yes
  retries: 2
  tags: [mpich]


# create user
- name: create user for mpich
  user:
    name: "{{ mpichuser }}"
    shell: /bin/bash
  become: yes
  tags: [mpich]


# user homedir perm
- name: fix homedir perms
  file:
    path: "/home/{{ mpichuser }}/"
    state: directory
    mode: 0700
  become: yes
  tags: [mpich]


# bin folder
- name: bin dir
  file:
    path: "/home/{{ mpichuser }}/bin/"
    state: "directory"
    mode: 0755
    owner: "{{ mpichuser }}"
    group: "{{ mpichuser }}"
  become: yes
  tags: [mpich]


# user ssh key pair
- name: create keypair
  user:
    name: "{{ mpichuser }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
  tags: [mpich]


# saves to /opt/cluster/backup/<host>/home/{{ mpichuser }}/.ssh/ (on the deployer node)
- name: fetch the ssh public key
  fetch:
    src: "/home/{{ mpichuser }}/.ssh/id_rsa.pub"
    dest: /opt/cluster/backup
  become: yes
  tags: [mpich]


- name: Add mpiuser to sshd users group
  user:
    name: "{{ mpichuser }}"
    groups: sshusers
    append: yes
  become: yes
  tags: [mpich]


- import_tasks: mpi-test-code.yml


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [mpich]
