---

# i don't recall where I found this PoC script


# mpi_sample.c
- name: copy mpi_sample.c
  copy:
    src: mpi_sample.c
    dest: "/home/{{ mpichuser }}/mpi_sample.c"
    owner: "{{ mpichuser }}"
    group: "{{ mpichuser }}"
    mode: 0644
  become: yes
  tags: [mpich]


# Check mpi_sample.c
- name: check mpi_sample
  stat:
    path: "/home/{{ mpichuser }}/bin/mpi_sample.c"
  register: mpi_sample_c
  changed_when: False
  become: yes
  tags: [mpich]


# make mpi_sample.c
- name: compile mpi_sample
  command: mpic++ -o ~/bin/mpi_sample mpi_sample.c
  args:
    chdir: "/home/{{ mpichuser }}/"
  when: mpi_sample_c.stat.exists == False
  become: yes
  become_user: "{{ mpichuser }}"
  tags: [mpich]
