---

# mpi_sample.c
- name: copy mpi_sample.c
  copy:
    src: mpi_sample.c
    dest: "/home/{{ rpi_clust_user }}/mpi_sample.c"
    owner:
    group:
    mode: 0644
  become: true
  tags: [mpich]


# make mpi_sample.c
- name: compile mpi_sample
  shell: mpic++ -o ~/mpi_sample ~/mpi_sample.c
  args:
    chdir: "/home/{{ rpi_clust_user }}/"
    creates: "/home/{{ rpi_clust_user }/mpi_sample"
  become: true
  become_user: "{{ rpi_clust_user }}"
  tags: [mpich]
