---
#
# "distcc is a program to distribute compilation of C or C++ code across several
# machines on a network. distcc should always generate the same results as a
# local compile, is simple to install and use, and is often two or more times
# faster than a local compile. "
#
# https://github.com/distcc/distcc

- debug: msg="DistCC Role "
  tags: [distcc]


- name: install distcc
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - distcc
    - distcc-pump
  retries: 2
  become: true
  tags: [distcc]


- name: distcc config
  template:
    src: distcc_conf.j2
    dest: /etc/default/distcc
    mode: 0644
    owner: root
    group: root
  become: true
  notify: distcc-restart
  tags: [distcc]


- name: distcc hosts file for compute node
  template:
    src: hostscompute.j2
    dest: /etc/distcc/hosts
    mode: 0644
    owner: root
    group: root
  become: true
  notify: distcc-restart
  tags: [distcc]


- name: distcc_test test script
  template:
    src: distcc_test.j2
    dest: /opt/cluster/bin/distcc_test.sh
    mode: 0755
  notify: distcc-restart
  tags: [distcc]


- name: rpi kernel build script
  template:
    src: distcc_kern.j2
    dest: /opt/cluster/bin/distcc_kern.sh
    mode: 0755


- name: distcc enabled on boot
  service: name=distcc enabled=yes
  become: true
  tags: [distcc]


- name: distcc started
  service: name=distcc state=started
  become: true
  tags: [distcc]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [distcc]
