---
- debug: msg="golang armv6l install role "
# # https://golang.org/dl/


- name: check if go installed
  stat: path=/usr/local/go/bin/go
  register: go_bin_usrlocal


- name: download go binary
  get_url:
    url: https://storage.googleapis.com/golang/go1.7.linux-armv6l.tar.gz
    dest: /opt/cluster/mysrc/
    checksum: sha256:4192592728e2f9fac8ae43abedb4b98d811836c3965035e7cb8c603aa5e65be4
  when: go_bin_usrlocal.stat.exists == False


- name: check if go installed
  stat: path=/usr/local/go/bin/go
  register: go_bin_usrlocal


- name: unarchive go
  become: yes
  unarchive:
    src: /opt/cluster/mysrc/go1.7.linux-armv6l.tar.gz
    dest: /usr/local/
    remote_src: True
  when: go_bin_usrlocal.stat.exists == False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
  become: yes
