# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "berrycluster"
license = "MIT"
description = "Raspberry Pi Cluster"
homepage = "www.b3rry.clust0r"
tags = []
features = []
min_version = "0.21"
SectionPagesMenu = "main"

[author]
  name = "crgm"
  homepage = "www.b3rry.clust0r"
