---
# config json
- debug: msg="consul config "


# servers
- name: conf config_server.json (server)
  template:
    src: config_server.j2
    dest: /opt/consul/consul.d/config_server.json
    mode: 0644
    owner: consul
    group: consul
  become: yes
  notify: restart-consul
  tags: [consul]
  when: "'consul_server' in group_names"


# servers
- name: conf config_server.json (server)
  template:
    src: config_server.j2
    dest: /opt/consul/consul.d/config_server.json
    mode: 0644
    owner: consul
    group: consul
  become: yes
  notify: restart-consul
  tags: [consul]
  when: "'consul_boot' in group_names"


# clients
- name: conf config_client.json (client)
  template:
    src: config_client.j2
    dest: /opt/consul/consul.d/config_client.json
    mode: 0644
    owner: consul
    group: consul
  become: yes
  notify: restart-consul
  tags: [consul]
  when: "'consul_client' in group_names"
