---


# Started
- name: consul started
  service:
    name: consul
    state: started
  become: yes
  register: consulstarted
  tags: [consul]
  when: rpi_conul_enabled == True


# wait for daemon to start
- name: pause after restart
  pause:
    seconds: 30
  tags: [consul]
  when: consulstarted.changed


# enabled on boot
- name: enable consul systemd script
  systemd:
    name: consul
    enabled: yes
    masked: no
  become: yes
  tags: [consul]
  when: rpi_conul_enabled == True


# stop if flagged off
- name: consul diabled
  service:
    name: consul 
    state: stopped
  become: yes
  tags: [consul]
  when: rpi_conul_enabled == false


# disable on boot if flagged off
- name: disable consul systemd script
  systemd:
    name: consul
    enabled: no
    masked: no
  become: yes
  tags: [consul]
  when: rpi_conul_enabled == false
