---
# NTP server
# http://www.ntp.org/
# http://www.pool.ntp.org/en/
- debug: msg="NTP Server "


# install
- name: ntp installed
  apt:
    name: ntp
    state: present
  become: true
  tags: [ntp]


# config file - Servers
- name: ntpd SERVER conf
  template:
    src: ntp_server.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
  become: true
  notify: ntp_restart
  tags: [ntp]


# started + enabled
- name: ntp started
  service:
    name: ntp
    state: started
    enabled: true
  become: true
  tags: [ntp]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [ntp]
