---
# tasks just for psi R-Pi
- debug: msg="psi node setup "
  tags: [host-psi]


- name: copy rpi_cluster code
  synchronize:
    src: ~/rpi_cluster/
    dest: ~/rpi_cluster/
    rsync_opts:
      - "--no-motd"
      - "--exclude=~/rpi_cluster/.git"
      - "--exclude=~/rpi_cluster/.vagrant/"
      - "--exclude=~/rpi_cluster/.DS_Store"
      - "--exclude=~/rpi_cluster/ignore_me/"
      - "--exclude=~/rpi_cluster/local_data/"
      - "--exclude=~/rpi_cluster/code/hugo-side/node_modules/"
  changed_when: False
  tags: [host-omega]


- name: copy firewall script
  template:
    src: ufw.j2
    dest: /root/ufw.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  changed_when: False
  tags: [host-psi]


- name: run firewall script
  shell: /root/ufw.sh
  args:
    chdir: /root/
    creates: /root/.ufw
  become: yes
  tags: [host-psi]


- name: output to rpicluster log
  shell: logger -t rpicluster host-psi role ran
  changed_when: False
  tags: [host-psi]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [host-psi]
