---
# tasks just for Omega


- debug: msg="Omega node setup "
  tags: [host-omega]


- name: install programs
  apt: name={{ item }} state=present
  with_items:
       - tcpdump
       - sense-hat
       - python-pycurl
       - siege
       - nmap
  retries: 1
  become: yes
  tags: [host-omega]


- name: copy firewall script
  template:
    src: ufw.j2
    dest: /root/ufw.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  changed_when: False
  tags: [host-omega]


- name: run firewall script
  shell: /root/ufw.sh
  args:
    chdir: /root/
    creates: /root/.ufw
  become: yes
  tags: [host-omega]


# Copy SenseHat welcome script
- name: copy sensehat welcome
  copy:
    src: sensehat-welcome.py
    dest: /opt/cluster/bin/sensehat-welcome.py
    mode: 0755
    owner: pi
    group: pi
  tags: [host-omega]


- name: run sensehat welcome
  shell: /opt/cluster/bin/sensehat-welcome.py
  tags: [host-omega]


# note: code runs from /opt/omegapyapi/app/
- name: copy omegapyapi code
  synchronize:
    src: ~/rpi_cluster/code/omegapyapi
    dest: /srv/python/
  changed_when: False
  tags: [host-omega]


- name: run omegapyapi installer
  shell: /srv/python/omegapyapi/install.sh
  args:
    chdir: /srv/python/omegapyapi
    creates: /opt/omegapyapi/omegapyapi.socket
  tags: [host-omega]


- name: omegapyapi service started
  service: name=omegapyapi state=started
  become: yes
  tags: [host-omega]


- name: omegapyapi enabled on boot
  service: name=omegapyapi enabled=yes
  become: yes
  tags: [host-omega]


# cron scripts
#- import_tasks: cron.yml
#  tags: [host-omega]


# php pub
- name: create /srv/php/omegaapp/pub
  file:
    path: "/srv/php/omegaapp/pub"
    state: "directory"
    mode: 0755
    owner: pi
    group: pi
  become: yes
  tags: [host-omega]


- name: upload omega php file
  copy:
    src: omega_info.php
    dest: /srv/php/omegaapp/pub/omega_info.php
    owner: pi
    group: pi
    mode: 0644
  tags: [host-omega]


- name: output to rpicluster log
  shell: logger -t rpicluster host-Omega role ran
  changed_when: False
  tags: [host-omega]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [host-omega]
