---
# tasks just for Omega
- debug: msg="Omega node setup "
  tags: [host-omega]


- name: install extra programs on omega
  apt:
    name: {{ item }} 
    state: present
  with_items:
       - tcpdump
       - lynx
       - sense-hat
       - python-pycurl
       - siege
       - nmap
  retries: 2
  become: yes
  tags: [host-omega]


- name: copy firewall script
  template:
    src: ufw.j2
    dest: /root/ufw.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  changed_when: False
  tags: [host-omega]


- name: run firewall script
  shell: /root/ufw.sh
  args:
    chdir: /root/
    creates: /root/.ufw
  become: yes
  tags: [host-omega]


# Raspberry Pi Astro SenseHAt
- import_tasks: sensehat.yml
  tags: [sensehat]


# omegapyapi
- import_tasks: omegapyapi.yml
  tags: [omegapyapi]


# cron scripts
- import_tasks: cron.yml
  tags: [host-omega]


# php pub
- name: create /srv/php/omegaapp/pub
  file:
    path: "/srv/php/omegaapp/pub"
    state: "directory"
    mode: 0755
    owner: pi
    group: pi
  become: yes
  tags: [host-omega]


- name: upload omega php file
  copy:
    src: omega_info.php
    dest: /srv/php/omegaapp/pub/omega_info.php
    owner: pi
    group: pi
    mode: 0644
  tags: [host-omega]


- name: output to rpicluster log
  shell: logger -t rpicluster host-Omega role ran
  changed_when: False
  tags: [host-omega]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [host-omega]
