---
# tasks just for Omega


- debug: msg="Omega node setup "
  tags: [host-omega]


- name: install programs
  apt: name={{ item }} state=present
  with_items:
       - sense-hat
       - python-pycurl
  retries: 1
  become: yes
  tags: [host-omega]


- name: copy omegapyapi code
  synchronize:
    src: ~/rpi_cluster/code/omegapyapi
    dest: /srv/python/omegapyapi
  changed_when: False
  tags: [host-omega]


# note: code runs from /opt/omegapyapi/app/


- name: run omegapyapi installer
  shell: /srv/python/omegapyapi/install.sh
  args:
    chdir: /srv/python/omegapyapi
    creates: /opt/omegapyapi/omegapyapi.socket
  tags: [host-omega]


- name: omegapyapi service started
  service: name=omegapyapi state=started
  become: yes
  tags: [host-omega]


- name: omegapyapi enabled on boot
  service: name=omegapyapi enabled=yes
  become: yes
  tags: [host-omega]


- name: output to rpicluster log
  shell: logger -t rpicluster host-Omega role ran
  changed_when: False
  tags: [host-omega]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [host-omega]
