---
# confd
# https://github.com/kelseyhightower/confd/


# check if we have installed yet
- name: check for confd binary
  stat: path=/usr/local/bin/confd
  register: confdbin
  tags: [confd]


# create etc folders
- name: /etc/confd/
  file: path=/etc/confd/ state=directory mode=0755 owner=root group=root
  become: yes
  tags: [confd]


- name: /etc/confd/conf.d/
  file: path=/etc/confd/conf.d/ state=directory mode=0755 owner=root group=root
  become: yes
  tags: [confd]


- name: /etc/confd/templates/
  file: path=/etc/confd/templates/ state=directory mode=0755 owner=root group=root
  become: yes
  tags: [confd]


# install script
- name: copy install script
  template: src=install_confd.j2 dest=/opt/cluster/mysrc/install_confd.sh mode=0755
  tags: [confd]


# run installer if bin missing
- name: run install script
  script: /opt/cluster/mysrc/install_confd.sh
  tags: [confd]
  when: confdbin.stat.exists == False


# templates
- include: templates.yml
  tags: [confd]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
  become: yes
