---
galaxy_info:
  role_name: puppet-agent
  author: crgm
  description: install the puppet agent
  company: crgm inc
  license: license (no)
  min_ansible_version: 2.8
  platforms:
  - name: Raspbian
    versions:
      - stretch
