---
# Install Hugo, a static site generator.
# https://gohugo.io/


- name: check we have hugo deb
  stat:
    path: "/opt/cluster/mysrc/{{ hugo_bin }}"
  register: hugo_apt_mysrc
  changed_when: False


- name: download Hugo bin if missing
  get_url:
    url: "{{ hugo_bin_url }}"
    dest: /opt/cluster/mysrc/
    checksum: "{{ hugo_bin_sha }}"
  when: hugo_apt_mysrc.stat.exists == False
  register: hugo_bin_dl
  tags: [hugo]


- name: Install a hugo deb package
  apt:
    deb: "/opt/cluster/mysrc/{{ hugo_bin }}"
  become: true
  when: hugo_bin_dl.changed
  tags: [hugo]


- name: get hugo version
  command: /usr/local/bin/hugo version
  register: hugoversion
  become: false
  changed_when: false
  ignore_errors: true
  tags: [hugo]


- name: check hugo ok
  assert:
    that:
      - "'Hugo Static Site Generator' in hugoversion.stdout"


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [hugo]
