---
# Users public and private SSH keys
- debug: msg="ssh (keys) "
  tags: [ssh]


# check for ~/.ssh/id_rsa
- name: check ssh private key
  stat: path="~/.ssh/id_rsa"
  register: sshprivkeyexists


# generate ssh key for current user if missing
- name: Generate a SSH key pair for this user
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ~/.ssh/id_rsa
  tags: [common,commonssh,ssh]
  when:
    - sshprivkeyexists.stat.exists == false
    - "'deploy' not in group_names"
  register: gen_ansible_user_ssh


- name: check ssh backup
  stat: path="/opt/cluster/data/{{ inventory_hostname }}_ssh_bu.tgz"
  register: sshpribackup
  become: yes


# backup generated key and ~/.ssh/
- name: backup user ssh dir on remote host
  archive:
    path: /home/{{ ansible_user_id }}/.ssh/
    dest: "/opt/cluster/data/{{ inventory_hostname }}_ssh_bu.tgz"
    owner: root
    group: root
    mode: 0440
  become: yes
  when: sshpribackup.stat.exists == false


# Saves to /opt/cluster/backup/<host>/home/<user>/.ssh/
- name: fetch the ssh public key
  fetch:
    src: ~/.ssh/id_rsa.pub
    dest: /opt/cluster/backup
