---
# Yarn - https://yarnpkg.com/en/
- debug: msg="deployer (yarn) "


# src folder
- name: create /opt/cluster/mysrc/yarn/
  file:
    path: /opt/cluster/mysrc/yarn/
    state: directory
    mode: 0755


- name: copy yarn gpg key to server also
  copy:
    src: yarnkey.asc
    dest: /opt/cluster/mysrc/yarn/yarnkey.asc
    mode: 0644


- name: Add yarn apt key
  apt_key:
    data: "{{ lookup('file', '/opt/cluster/mysrc/yarn/yarnkey.asc') }}"
    state: present
  become: true


- name: add yarn apt repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  become: true
  register: yarnaddapt


- name: yarn packages installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - yarn
  become: true
  retries: 2


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible yarn role ran
  changed_when: False