---
# Yarn - https://yarnpkg.com/en/
- debug: msg="deployer (yarn) "



- name: Add yarn apt key
  apt_key:
    data: "{{ lookup('file', 'yarnkey.asc') }}"
    state: present
  become: true


- name: add yarn apt repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  become: true


- name: yarn packages installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - yarn
  become: true
  retries: 2


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible yarn role ran
  changed_when: False