---
# Trackuptime - use "uprecords" command to view.
- debug: msg="uptimed "


- name: install uptimed
  apt: state=present name=uptimed
  become: yes
  tags: uptimed


- name: uptimed enabled on boot
  service: name=uptimed enabled=yes
  become: yes
  tags: uptimed


- name: uptimed restarted
  service: name=uptimed state=restarted
  become: yes
  changed_when: False
  tags: uptimed


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: uptimed
