---
# Trackuptime - use "uprecords" command to view.
- debug: msg="uptimed "


- name: install uptimed
  apt:
    state: present
    name: uptimed
  become: yes
  tags: uptimed


- name: enable uptimed on boot
  service:
    name: uptimed
    state: started
    enabled: yes
  become: yes
  tags: uptimed


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: uptimed
