---
# haveged - random number generator
# http://www.issihosts.com/haveged/
- debug: msg="common (haveged) "


- name: install haveged
  apt: state=present name=haveged
  tags: install
  become: yes
  register: aptinsthaveged


- name: haveged enabled on boot
  service: name=haveged enabled=yes
  become: yes


- name: haveged started
  service: name=haveged state=started
  become: yes


- name: notify rpicluster log
  shell: logger -t rpicluster installed haveged
  changed_when: false
  when: aptinsthaveged.changed


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
    owner: root
    group: root
    mode: 0444
  become: yes
