---
# haveged - random number generator
# http://www.issihosts.com/haveged/


- debug: msg="common (haveged) "


- name: install haveged
  apt: state=present name=haveged
  become: yes
  register: aptinsthaveged
  tags: haveged


- name: haveged enabled on boot
  service: name=haveged enabled=yes
  become: yes
  tags: haveged


- name: haveged started
  service: name=haveged state=started
  become: yes
  tags: haveged


- name: notify rpicluster log
  shell: logger -t rpicluster installed haveged
  changed_when: false
  when: aptinsthaveged.changed
  tags: haveged


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: haveged
