---
# maintenance role
- debug: msg="maintenance role "


# log
- name: output to rpicluster log
  command: logger -t rpicluster starting upgrade role
  changed_when: False
  tags: [maintenance]


# apt packages
- import_tasks: package_apt.yml

# ruby gems
#- import_tasks: package_gem.yml

# python pip
#- import_tasks: package_pip.yml


# Update R-Pi firmware in /boot/
# (I've found that, on occasion, this will prevent the Pi from booting)
#- name: update kernel
#  shell: SKIP_WARNING=1 /usr/bin/rpi-update
#  become: true
#  tags: [maintenance]
#  when: "'deployer' not in group_names"


# systemctl daemon-reload
- name: force systemd to reread all configs
  systemd:
    daemon_reload: true
  become: true
  tags: [maintenance]
  when: apt_upgraded.changed
  changed_when: False


# check system units OK
- name: check for failed system services
  command: /bin/systemctl list-units --all --state=failed
  become: true
  changed_when: False
  register: systemctl_failed_units
  failed_when: "'0 loaded units listed.' not in systemctl_failed_units.stdout"


# log
- name: output to rpicluster log
  command: logger -t rpicluster finished upgrade role OK
  changed_when: False
  tags: [maintenance]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [maintenance]
