# ----------------------------- #
# --- rpi-py-api Dockerfile --- #
# ----------------------------- #

FROM python:3

ENV DEBIAN_FRONTEND noninteractive

# create the user "rpyapi" for the app to run as
RUN groupadd -r rpyapi && \
    useradd -r -g rpyapi -d /app -s /sbin/nologin -c "rpyapi" rpyapi

ENV HOME=/app

# Copy the appsrc directory contents into the container at /app
COPY appsrc /app

# Set the working directory to /app
WORKDIR /app

RUN mkdir /logs/

RUN chown -R rpyapi:rpyapi /app/ /logs/

# install app requirements
RUN pip install -r /app/requirements.txt

USER rpyapi

# entry point - launch gunicorn
CMD ["bash", "/app/start.sh"]

EXPOSE 8382

# EOF