---
- debug: msg="Base System apt-repo"


- name: apt-repo remove default repository
  apt_repository:
    repo: deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
    state: absent
  become: true


- name: apt-repo add raspbian mirror
  apt_repository:
    repo: "deb {{ apt_local_mirror }} stretch main contrib non-free rpi"
    state: present
    update_cache: true
  become: true


- name: copy apt config
  copy:
    src: etc/apt/apt.conf.d/00local-rpi-cluster
    dest: /etc/apt/apt.conf.d/00local-rpi-cluster
    mode: 0644
    owner: root
    group: root
  become: true