---
- debug: msg="Base System apt-repo"


- name: apt-repo remove default repository
  apt_repository:
    repo: deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi
    state: absent
  become: yes


- name: apt-repo add raspbian mirror
  apt_repository:
    repo: "deb {{ apt_local_mirror }} stretch main contrib non-free rpi"
    state: present
    update_cache: yes
  become: yes
