---
- debug: msg="Base System cleanup"


# Remove Apt packages (in defaults/main.yml)
- name: Remove these packages
  apt:
    name: "{{ item.rmapt }}"
    state: absent
  with_items: "{{ package_remove }}"
  become: yes


- name: disable bluetooth
  systemd:
    name: bluetooth
    enabled: no
    masked: no
  become: yes
  tags: [kernelmod]
  ignore_errors: yes


- name: stop these services
  service:
    name: "{{ item.name }}"
    state: stopped
    enabled: no
  with_items: "{{ services_to_stop }}"
  changed_when: false
  become: yes