---
# files/folders on all nodes
- debug: msg="Base System filesfolders"


# fix home dir defaults of drwxr-xr-x
- name: fix homedir perms
  file:
    path: "/home/{{ ansible_user_id }}/"
    state: directory
    mode: 0700


# create /opt/cluster/
- name: R Pi cluster base dir
  file:
    path: /opt/cluster/
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0770
  become: yes


# create folders
- name: Create common folders
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ common_dir }}"
  become: yes


# specific folders for this host
- name: Create specific folders for this host
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ host_dir }}"
  become: yes


# copy ~/. dot files
- name: dot files in home dir
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ dotfiles }}"


# copy bash scripts
- name: copy bash scripts
  copy:
    src: "files/bash-script/{{ item.file }}"
    dest: "/opt/cluster/bin/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ binfile }}"


# detect R-Pi MAC - rpihw.fact
- name: copy rpihw.fact
  copy:
    src: rpihw.fact
    dest: /etc/ansible/facts.d/rpihw.fact
    mode: 0775
    owner: root
    group: root
  become: yes
  changed_when: False


# so the fact above is available
- name: reload ansible_local
  setup:
    filter: ansible_local


- name: etc rc.local
  template:
    src: etc/rc_local.j2
    dest: "/etc/rc.local"
    mode: 0750
    owner: root
    group: root
  become: yes
  changed_when: False


- name: copy etc issue
  copy:
    src: etc/issue
    dest: /etc/issue
    mode: 0644
    owner: root
    group: root
  become: yes


# create info_roles.txt
- name: info_roles txt
  copy:
    content: "--==[ Ansible Roles run against this host ]==--"
    dest: /opt/cluster/data/info_roles.txt
    force: no
    mode: 0444
    owner: root
    group: root
  become: yes


# info_host.txt
- name: info_host txt
  template:
    src: rpihost.j2
    dest: "/opt/cluster/data/info_host.txt"
    mode: 0444
    owner: root
    group: root
  become: yes
  changed_when: False


# fetch
- name: fetch info_host
  fetch:
    src: /opt/cluster/data/info_host.txt
    dest: /opt/cluster/backup
  changed_when: false
