---
- debug: msg="Base System kernelmod"


# change in role vars folder
- name: blacklist these kernel modules
  kernel_blacklist:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ kern_blacklist_mod }}"
  become: true
  ignore_errors: true
  tags: [kernelmod]
