---
- debug: msg="Base System kernelmod"


# change in role vars folder
- name: blacklist these kernel modules
  kernel_blacklist:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ kern_blacklist_mod }}"
  become: yes
  ignore_errors: yes
  tags: [kernelmod]


- name: enable watchdog timer module
  modprobe:
    name: bcm2835_wdt
    state: present
  become: yes
  tags: [kernelmod]