---
# Common OS configuration for _all_ nodes
# Files and folder structures, pacakges


- debug: msg="Base System main"
  tags: [common]


- name: check OS is Debian family
  assert:
    that:
      - "ansible_os_family == 'Debian'"


- name: Verify min ansible version requirements.
  assert:
    that: "ansible_version.full is version_compare('2.8', '>=')"
    msg: >
      "Upgrade ansible, this version is not supported"


# sub-tasks --------------------------------------------------------------------

# set timzone and language etc
- import_tasks: localization.yml

# /etc/hosts and system hostname
- import_tasks: hostsname.yml

# file structure
- import_tasks: filesfolders.yml

# blacklist/load kernel modules on R-Pi Hardware
- import_tasks: kernelmod.yml

# /etc/sysctl.conf tuning
- import_tasks: sysctl.yml

# Apt repo setup
- import_tasks: apt-repo.yml

# Install Apt packages
- import_tasks: apt-packages.yml

# remove unwanted packages and services
- import_tasks: cleanup.yml

# pki
#- import_tasks: sslcert.yml

#-------------------------------------------------------------------------------


# rpi config.txt gpu memory setting
- name: reduce mem allocated to gpu
  lineinfile:
    path: /boot/config.txt
    regexp: '^gpu_mem='
    line: 'gpu_mem=16'
  become: yes


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible base-system roll ran
  tags: [common]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  changed_when: False
  become: yes
  tags: [common]
