---
# Raspbian /etc/sysctl.conf tuning
- debug: msg="Base System sysctl"


# change in role vars folder
- name: change etc sysctl conf settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set:  "{{ item.set }}"
    state: "{{ item.state }}"
    reload: true
  with_items: "{{ sysctl_settings }}"
  become: true
