---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: debian:10
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    x: ["ANSIBLE503"]
verifier:
  name: testinfra
  lint:
    name: flake8
