---
# handle hostname
- debug: msg="Common (hostsname) "


- name: get my current hostname
  command: hostname
  register: my_current_hostname
  changed_when: False

- debug: msg="my_current_hostname {{ my_current_hostname}} "


- name: set-hostname with hostnamectl
  command: hostnamectl set-hostname {{ inventory_hostname }}
  become: true
  changed_when: False


- name: set-locations with hostnamectl
  command: hostnamectl set-location {{ rpi_racked }}
  become: true
  changed_when: False
  when: "'delploy' not in group_names"


- name: set-chassis with hostnamectl
  command: hostnamectl set-chassis embedded
  become: true
  changed_when: False
  when: "'delploy' not in group_names"


# Reboot if hostname is default "raspberrypi"
- name: reboot if hostname was default
  shell: sleep 2 && reboot now
  become: true
  async: 30
  poll: 0
  ignore_errors: true
  when: my_current_hostname == "raspberrypi"
  register: rebooted_rpi

# longer pause between lanservices
- name: pause
  pause:
    seconds: 60
  when:
    - my_current_hostname == "Raspberry"
    - rebooted_rpi.changed

# wait for host
- name: wait for host to restart
  wait_for:
    host: '{{hostvars[item].ansible_host}}'
    port: 22
    state: started
    delay: 30
    timeout: 150
  with_items: '{{play_hosts}}'
  connection: local
  when:
    - my_current_hostname == "Raspberry"
    - rebooted_rpi.changed
    

# /etc/hosts file
- name: etc hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: "'vagrantvm' not in group_names"
  become: true
