---
# HAProxy - http://www.haproxy.org/
- debug: msg="HAProxy install "
  tags: [haproxy]


- name: check these keys exist
  assert:
    that:
    - haproxy_cfg_file is defined


# install
- name: install haproxy server packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - haproxy
       - haproxyctl
  become: yes
  retries: 1
  tags: [haproxy]


# ssl dir
- name: ssl dir
  file:
    path: /etc/haproxy/ssl
    state: directory
    mode: 0760
    owner: root
    group: haproxy
  become: yes
  tags: [haproxy]


# config file (checked below)
- name: haproxy config
  template:
    src: "{{ haproxy_cfg_file }}/haproxy.j2"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: haproxy
    mode: 0664
    backup: yes
  become: yes
  notify: haproxy-restart
  register: haproxycfg_change
  tags: [haproxy]


# log if config changes
- name: notify rpicluster log
  command: logger -t rpicluster haproxy config changed
  changed_when: false
  when: haproxycfg_change.changed
  tags: [haproxy]


# self signed cert
- name: check for ssl cert
  stat: 
    path: /etc/haproxy/ssl/default_cert.pem
  register: haproxy_ss_ssl
  become: yes
  tags: [haproxy]


- name: haproxy enabled on boot and started
  service:
    name: haproxy
    enabled: yes
    state: started
  become: yes
  tags: [haproxy]


# check haproxy config file
- name: test haproxy config file
  command: haproxyctl configcheck
  register: haproxycnf_result
  become: yes
  changed_when: false
  failed_when:
    - "'Configuration file is valid' not in haproxycnf_result.stdout"
  tags: [haproxy]


# log
- name: notify rpicluster log
  command: logger -t rpicluster installed haproxy with {{ haproxy_cfg_file }} config
  changed_when: false
  tags: [haproxy]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [haproxy]
