---
# Run at the end of each playbook

- name: Refresh inventory
  meta: refresh_inventory


- debug: msg="ansible-post-role "
  tags: [ansiblepost]


# keep a tally of how many times ansible has run
- name: increment rpi deployer ansible runcount
  command: /usr/bin/redis-cli incr /rpi/deployer/ansible/runcount
  delegate_to: localhost
  ignore_errors: False
  check_mode: no
  changed_when: False
  tags: [ansiblepost]
  run_once: True
