---
- debug: msg="golang armv6l install role "
# https://golang.org/dl/


- name: check we have go src
  stat:
    path: "/opt/cluster/mysrc/{{ goland_targz }}"
  register: go_src_current
  changed_when: False
  tags: [golang]


- name: download go binary
  get_url:
    url: https://dl.google.com/go/{{ goland_targz }}
    dest: /opt/cluster/mysrc/
    checksum: "{{ golang_shasum }}"
  when:
    - "go_src_current.stat.exists == False"
  tags: [golang]


- name: unarchive go
  become: yes
  unarchive:
    src: /opt/cluster/mysrc/{{ goland_targz }}
    dest: /usr/local/
    creates: /usr/local/go/
    remote_src: True
  tags: [golang]


- name: add golang bin to environment path
  command: go version
  environment:
    PATH: $PATH:/usr/local/go/bin
  changed_when: false
  tags: [golang]


- name: system wide PATH
  copy:
    dest: /etc/profile.d/golang-path.sh
    content: 'export PATH=$PATH:/usr/local/go/bin'
  become: yes
  tags: [golang]


- name: copy build_go_hello
  template:
    src: build_go_hello.j2
    dest: /opt/cluster/bin/build_go_hello.sh
    mode: 0755
  tags: [golang]


- name: run build_go_hello
  script: /opt/cluster/bin/build_go_hello.sh
  args:
    creates: /home/pi/go/src/hello/hello
  tags: [golang]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [golang]
