---
- debug: msg="ufw rules for Compute group "


# for Docker network addons - allow all inernal subnets

- name: Allow internal subnets
  ufw:
    rule: allow
    src: '{{ item }}'
  notify: ufw_restart
  become: yes
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
