---
- debug: msg="ufw rules for lanservice misc "


- name: Deny access these ports
  ufw:
    rule: deny
    port: '{{ item }}'
    comment: lanservice_misc deny port
  become: yes
  with_items:
    - '3306'
    - '6379'
    - "{{ nginx_port }}"
    - "{{ nginx_port2 }}"
  notify: ufw_restart


# Local subnet can hit anything listening here
- name: Allow all access on local subnet
  ufw:
    rule: allow
    src: "{{ rpi_net_id }}/{{ rpi_net_maskbit }}"
    comment: lanservice_misc group allows local subnet
  notify: ufw_restart
  become: yes


- name: Allow internal subnet access to webserver
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    src: '{{ item }}'
  notify: ufw_restart
  become: yes
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16