---
# Install the "modules" software.
#
# https://en.wikipedia.org/wiki/Environment_Modules_(software)
# https://modules.readthedocs.io/en/stable/index.html


- name: install modules software
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - environment-modules
       - lmod
       - lua-posix
  retries: 2
  become: yes


- name: Create folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ envmod_dir }}"
  become: yes


- name: add MODULEPATH to bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export MODULEPATH=/opt/cluster/modulefiles/:$MODULEPATH'
    create: yes
