---
# https://coreos.com/etcd/
# https://github.com/coreos/etcd


# check etcd tar.gz exists
- name: check etcd zip
  stat: path=/opt/cluster/mysrc/{{ etcd_url_targz }}
  register: check_etcd_targz
  tags: [etcd]


# download etcd tar.gz src
- name: download etcd
  get_url:
    url: "{{ etcd_url_path }}{{ etcd_url_targz }}"
    dest: /opt/cluster/mysrc/
    checksum: sha256:{{ etcd_targz_sha }}
  when: check_etcd_targz.stat.exists == False
  register: dl_etcd_targz
  tags: [etcd]


# check bin exists
- name: check consul bin
  stat: path=/usr/local/bin/etcd
  register: etcdbinlocal
  tags: [etcd]


# unzip source
- name: unarchive etcd
  unarchive:
    src: /opt/cluster/mysrc/{{ etcd_url_targz }}
    dest: /usr/local/bin/
    mode: 0755
    remote_src: yes
  when: etcdbinlocal.stat.exists == False
  become: yes
  tags: [etcd]
