---
# install kubernetes on compute nodes
- debug: msg="kubernetes setup on compute nodes "


- name: make folder structure
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ k8_dir }}"
  become: yes


# copy bash scripts
- name: copy bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/docker/scripts/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ bashscriptk8 }}"


# System prerequisites
- include: systemopts.yml


- name: setup kubernetes apt repo
  shell: /opt/cluster/docker/scripts/install-kube-apt.sh
  args:
    chdir: /opt/cluster/mysrc/
    creates: /etc/apt/sources.list.d/kubernetes.list
  register: installkubesh
  tags: [kube]


- name: pausing
  pause:
    seconds: 5
  when: installkubesh.changed
  tags: [kube]


- name: kubeadm packages installed
  apt:
    name: {{ item }}
    state: present
  with_items:
       - kubeadm
       - kubelet
       - kubectl
       - kubelet
       - kubernetes-cni
       - policykit-1
  become: yes
  retries: 2
  tags: [kube]
  register: kube_aptinst


- name: pause
  pause:
    seconds: 5
  when: kube_aptinst.changed
  tags: [kube]


- name: force systemd to reread configs
  systemd:
    daemon_reload: yes
  become: yes
  when: kube_aptinst.changed
  changed_when: False
  tags: [kube]


- name: restart kubelet.service
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet.service
  become: yes
  when: kube_aptinst.changed
  changed_when: False
  tags: [kube]


#-------------------------------------------------------------------------------

# docker_master group
- import_tasks: master_boss_node.yml
  tags: [kube,kubemaster]
  when:
    - "'docker_master' in group_names"
    - "rpi_docker_enabled == True"


# docker_worker group
- import_tasks: join_master.yml
  tags: [kube,kubemaster]
  when:
    - "'docker_worker' in group_names"
    - "rpi_docker_enabled == True"

#-------------------------------------------------------------------------------

# show nodes in cluster
- name: get nodes
  shell: kubectl get nodes
  tags: [kube]
  changed_when: False
  when:
    - "'docker_master' in group_names"
    - "rpi_docker_enabled == True"

# show pod servic
- name: kubectl get pods
  shell: kubectl get pods --namespace=kube-system
  tags: [kube]
  changed_when: False
  when:
    - "'docker_master' in group_names"
    - "rpi_docker_enabled == True"

#-------------------------------------------------------------------------------


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible kubernetes roll ran
  tags: [kube]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [kube]
