---
- debug: msg="Kubernetes master setup"

#-------------------------------------------------------------------------------
# init

# check if the cluster is alreadly initialized
- name: check for kube_info.txt
  stat: path=/opt/cluster/docker/kubecnf/kube_info.txt
  register: kube_info_txt
  changed_when: False


# initialize the cluster (if not yet)
- name: kubeadm init master node
  command: kubeadm init
  when:
    - "kube_info_txt.stat.exists == False"
    - "rpi_docker_enabled == True"
    - "'docker_master' in group_names"
  register: initialized_main_node
  become: yes


# pause after init
- name: pausing
  pause:
    seconds: 30
  when: initialized_main_node.changed


# save init info to kube_info.txt
- name: "initialization info"
  copy:
    content: "{{ initialized_main_node.stdout }}"
    dest: "/opt/cluster/docker/kubecnf/kube_info.txt"
  when:
    - initialized_main_node.changed
    - "kube_info_txt.stat.exists == False"
  register: created_kube_info_txt


# fetch init details
- name: fetch kube master api info
  fetch:
    src: /opt/cluster/docker/kubecnf/kube_info.txt
    dest: /opt/cluster/backup
  when:
    - created_kube_info_txt.changed

#-------------------------------------------------------------------------------

- name: pausing
  pause:
    seconds: 5

- name: run setup-kube.sh
  shell: /opt/cluster/docker/scripts/setup-kube.sh
  args:
    creates: /opt/cluster/docker/kubecnf/admin.conf

#-------------------------------------------------------------------------------
# Setup networking with Weave

- name: check for kube_net.txt
  stat: path=/opt/cluster/docker/kubecnf/kube_net.txt
  register: kube_net_txt
  changed_when: False

- name: weave networking
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" > /opt/cluster/docker/kubecnf/kube_net.txt
  when:
    - "kube_net_txt.stat.exists == False"
  register: kube_net_apply

# will take much longer to complete
- name: pausing
  pause:
    seconds: 45
  when: kube_net_apply.changed

#-------------------------------------------------------------------------------

- name: get cluster info
  shell: kubectl cluster-info
  changed_when: False


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible kubernetes master boss role ran
  changed_when: False
