---
- debug: msg="Kubernetes master setup"


# check if the cluster is alreadly initialized
- name: check for kube_info.txt
  stat: path=/opt/cluster/data/kube_info.txt
  register: kube_info_txt
  changed_when: False


# initialize the cluster (if not yet)
- name: kubeadm init master node
  command: kubeadm init
  when:
    - "kube_info_txt.stat.exists == False"
    - "rpi_docker_enabled == True"
    - "'docker_master' in group_names"
  register: initialized_main_node
  become: yes


# pause after init
- name: pausing
  pause:
    seconds: 15
  when: initialized_main_node.changed


# save init info to kube_info.txt
- name: "initialization info"
  copy:
    content: "{{ initialized_main_node.stdout }}"
    dest: "/opt/cluster/data/kube_info.txt"
  when:
    - initialized_main_node.changed
    - "kube_info_txt.stat.exists == False"
  register: created_kube_info_txt


# fetch init details
- name: fetch kube master api info
  fetch:
    src: /opt/cluster/data/kube_info.txt
    dest: /opt/cluster/backup
  when:
    - created_kube_info_txt.changed


- name: pausing
  pause:
    seconds: 5


- name: run setup-kube.sh
  shell: /opt/cluster/bin/setup-kube.sh
  args:
    chdir: /opt/cluster/bin/
    creates: /opt/cluster/data/.setup-kube


- name: get cluster info
  shell: kubectl cluster-info
  changed_when: False


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible kubernetes master boss role ran
  changed_when: False
