---
- debug: msg="k8Worker join a master node "


# get join command/API key
- name: k8Worker upload k8_rpi_join script
  copy:
    src: /opt/cluster/backup/epsilon/opt/cluster/docker/kubecnf/k8_rpi_join.sh
    dest: /opt/cluster/docker/kubecnf/k8_rpi_join.sh
    owner: pi
    group: pi
    mode: '0755'


# join cluster
- name: k8Worker run k8_rpi_join to join cluster
  shell: /opt/cluster/docker/kubecnf/k8_rpi_join.sh
  become: true
  register: join_kube_mast


# log
- name: k8Worker output to rpicluster log
  command: logger -t rpicluster ansible kubernetes join master roll ran
  changed_when: False
