---
- debug: msg="Kubernetes master setup"


# check if the cluster is alreadly initialized
- name: k8Master check for kube_info.txt
  stat: 
    path: "/opt/cluster/docker/kubecnf/kube_info.txt"
  register: kube_info_txt
  changed_when: False


# config
- name: k8Master kubeadm config
  copy:
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
    content: |
      Environment="KUBELET_EXTRA_ARGS=--enable-controller-attach-detach=false --cgroup-driver=systemd"
  become: yes
  tags: [kube]



# initialize the cluster (if not yet)
- name: k8Master init-kube.sh to create master node
  shell: /opt/cluster/docker/scripts/init-kube.sh
  args:
    creates: /opt/cluster/docker/kubecnf/k8_rpi_join.sh
  become: yes
  register: initialized_main_node
  failed_when:
    - initialized_main_node.rc != 0


# fetch init details
- name: k8Master fetch kube master api info
  fetch:
    src: /opt/cluster/docker/kubecnf/k8_rpi_join.sh
    dest: /opt/cluster/backup/
  when:
    - initialized_main_node.changed


# copy admin.conf so you can use kubectl
- name: k8Master run setup-kubectl.sh
  shell: /opt/cluster/docker/scripts/setup-kubectl.sh
  args:
    creates: /opt/cluster/docker/kubecnf/admin.conf


# setup networking
- name: k8Master init-kube-net.sh to create master node
  shell: /opt/cluster/docker/scripts/init-kube-net.sh
  args:
    creates: /opt/cluster/docker/kubeinit-net.txt
  become: yes
  when:
    - initialized_main_node.changed
  register: initialized_main_node_net
  failed_when:
    - initialized_main_node.rc != 0


# log
- name: k8Master output to rpicluster log
  command: logger -t rpicluster ansible kubernetes master boss role ran
  changed_when: False
