---
# uses inventory, but all actions are on localhost
- debug: msg="group deployer ssh "


- debug: msg="inventory_hostname {{ inventory_hostname }} "
  ignore_errors: True
  changed_when: False


- name: users ssh client config
  template: src=ssh_client_conf.j2 dest=~/.ssh/config
  delegate_to: localhost
  changed_when: False


- name: put inventory into etc hosts
  template: src=etc_hosts.j2 dest=/etc/hosts
  delegate_to: localhost
  become: yes
  changed_when: False


- name: empty known_hosts file
  shell: echo "" > ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True


- name: add host.local to known_hosts - StrictHostKeyChecking FALSE
  shell: ssh-keyscan {{ inventory_hostname }}.local >> ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True


- name: add host to known_hosts
  shell: ssh-keyscan -t ecdsa {{ inventory_hostname }} >> ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
