---
# uses inventory, but all actions are on localhost
- debug: msg="group deployer ssh "


- debug: msg="inventory_hostname {{ inventory_hostname }} "
  ignore_errors: True
  changed_when: False


- name: users ssh client config
  template:
    src: ssh_client_conf.j2
    dest: ~/.ssh/config
  delegate_to: localhost
  run_once: true


- name: put inventory into etc hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
  delegate_to: localhost
  become: yes
  run_once: true


- name: empty known_hosts file
  shell: echo "" > ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True
  run_once: true


- name: add host to known_hosts
  shell: ssh-keyscan {{ rpi_ip }} >> ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True
  run_once: true


- name: add host hostname to known_hosts
  shell: ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
  delegate_to: localhost
  changed_when: False
  ignore_errors: True
  run_once: true


- name: /etc/ethers
  template:
    src: etc/ethers.j2
    dest: /etc/ethers
    mode: 0644
  become: yes
  delegate_to: localhost
  register: static_arp_update
  run_once: true


- name: update state arp entries
  shell: /usr/sbin/arp -f /etc/ethers
  become: yes
  delegate_to: localhost
  when: static_arp_update.changed
  run_once: true


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  delegate_to: localhost
  run_once: true
