---
- debug: msg="NodeJS install "

# https://github.com/nodesource/distributions/blob/master/README.md


- name: create npm-global folder
  file:
    path: /srv/nodejs/
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  tags: [nodejs]


- name: create npm-global folder in opt
  file:
    path: /opt/npm-global/
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  tags: [nodejs]


# copy setup .sh
- name: copy nodejs installer
  copy:
    src: "{{ nodejs_setup_ver }}"
    dest: "/opt/cluster/mysrc/{{ nodejs_setup_ver }}"
    mode: 0755
  tags: [nodejs]


# run installer
- name: run nodejs_setup_x installer
  command: "/opt/cluster/mysrc/{{ nodejs_setup_ver }}"
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  become: true
  tags: [nodejs]


# install
- name: install nodejs packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
  become: true
  retries: 2
  tags: [nodejs]


- name: get nodejs version
  command: /usr/bin/nodejs --version
  register: nodejs_inst_ver
  changed_when: false
  tags: [nodejs]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [nodejs]
