---
# only used for nodes that have a static IP set,
# as this is where you set static IP's on Raspbian now.

- debug: msg="set static IP with dhcpcd "
- debug: msg="IP will be {{ hostvars[inventory_hostname]['rpi_ip'] }}"


# Network settings (static IP is set here)
- name: static ip in dhcp client opts
  template:
    src: dhcp-client.j2
    dest: /etc/dhcpcd.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
  become: yes
  tags: [dhcpclient]


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible dhcp-client role ran
  tags: [dhcpclient]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [dhcpclient]
