---
galaxy_info:
  role_name: ufw
  author: crgm
  description: install ufw to manage iptables and then setup some firewall rules
  company: crgm inc
  license: license (no)
  min_ansible_version: 2.8
  platforms:
  - name: Raspbian
    versions:
      - stretch
