---
# DHCP server -  Run by admin alpha and beta
#
# https://www.isc.org/downloads/dhcp/
# https://kb.isc.org/article/AA-01043/183/Recommendations-for-restarting-a-DHCP-failover-pair.html

- debug: msg="dhcp SERVER role "
- debug: msg="dhcpd status {{ rpi_dhcpd_status }} "


- name: install dhcp server
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - isc-dhcp-server
       - dhcpdump
  become: yes
  retries: 2
  register: dhcpd_new
  tags: [dhcpserver]


- name: dhcpd default config
  template:
    src: dhcp-server-default.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: isc-dhcp-server-reload
  tags: [dhcpserver]


- name: dhcpd config
  template:
    src: dhcpd.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    validate: /usr/sbin/dhcpd -t -cf %s
  become: yes
  notify: isc-dhcp-server-reload
  tags: [dhcpserver]


#-------------------------------------------------------------------------------

# enabled on boot (if flagged on)
- name: isc-dhcp-server enabled on boot
  service:
    name: isc-dhcp-server
    enabled: yes
  become: yes
  tags: [dhcpserver]
  when: rpi_dhcpd_enabled == true


# service stopped + off (if flagged off)
- name: isc-dhcp-server stopped
  service:
    name: isc-dhcp-server
    state: stopped
    enabled: no
  become: yes
  tags: [dhcpserver]
  when: rpi_dhcpd_enabled == false

#-------------------------------------------------------------------------------
# on first setup

# pause
- name: wait for hosts to get leases
  pause:
    seconds: 90
  tags: [dhcpserver]
  when:
    - dhcpd_new.changed
    - rpi_dhcpd_enabled == true


- name: Refresh inventory
  meta: refresh_inventory
  tags: [dhcpserver]
  when:
    - dhcpd_new.changed
    - rpi_dhcpd_enabled == true

#-------------------------------------------------------------------------------

# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible dhcp-server role ran
  tags: [dhcpserver]
  changed_when: false


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [dhcpserver]
