---
# For debugging, and running on all hosts to gather facts.


- meta: clear_host_errors


- name: ping
  ping:


- name: Refresh inventory
  meta: refresh_inventory


- name: "re-run setup "
  setup: ~


- debug: msg="inventory hostname {{ inventory_hostname }} "
  changed_when: False
  tags: [ansiblepre]
  ignore_errors: True


- debug: msg="ansible hostname {{ ansible_hostname }} "
  changed_when: False
  tags: [ansiblepre]
  ignore_errors: True


# syslog
- name: ansible pre role syslog
  syslogger:
    msg: "rpicluster ansible-pre-role gathering facts"
    priority: "notice"
    facility: "daemon"
    log_pid: true
  ignore_errors: True
  changed_when: False
  run_once: True
  tags: [ansiblepre]


- name: get rpi deployer ansible runcount
  local_action: command /usr/bin/redis-cli get /rpi/deployer/ansible/runcount
  run_once: True
  changed_when: False
  tags: [ansiblepre]
  ignore_errors: True


- name: store rpi IP in redis
  local_action: command /usr/bin/redis-cli set /rpi/{{ inventory_hostname }}/ip {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}
  changed_when: False
  run_once: True
  tags: [ansiblepre]
  ignore_errors: True


- name: store rpi MAC in redis
  local_action: command /usr/bin/redis-cli set /rpi/{{ inventory_hostname }}/mac {{ hostvars[inventory_hostname]['ansible_default_ipv4']['macaddress'] }}
  changed_when: False
  run_once: True
  tags: [ansiblepre]
  ignore_errors: True
