---
# For debugging, and running on all hosts to gather facts.


- meta: clear_host_errors


# ping all hosts in inventory
- name: ping
  ping:


- name: "re-run setup "
  setup: ~


- debug: msg="inventory hostname {{ inventory_hostname }} "
  changed_when: False
  tags: [ansiblepre]
  ignore_errors: True


- debug: msg="ansible hostname {{ ansible_hostname }} "
  changed_when: False
  tags: [ansiblepre]
  ignore_errors: True


# syslog
- name: ansible pre role syslog
  syslogger:
    msg: "rpicluster ansible-pre-role gathering facts"
    priority: "notice"
    facility: "daemon"
    log_pid: true
  ignore_errors: True
  changed_when: False
  run_once: True
  tags: [ansiblepre]
  delegate_to: localhost
