---


- name: download ossec src
  local_action:
   get_url:
     url: https://github.com/ossec/ossec-hids/archive/3.0.0.tar.gz
     dest: /opt/cluster/mysrc/
     checksum: sha256:a271d665ed502b3df4ff055a177159dfc0bc8a69dd44eab1f7c57fe8fff42a98
