---


- name: download ossec src
   get_url:
     url: "{{ ossec_bin_url }}"
     dest: /opt/cluster/mysrc/
     checksum: "{{ ossec_bin_sha }}"


- name: Extract archive
  unarchive:
    dest: /opt/cluster/mysrc/
    src: "/opt/cluster/mysrc/{{ ossec_bin_dl }}/"
    creates: /opt/cluster/mysrc/
    copy: no


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
