---
# Install MS .NET Core on R-Pi
# https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md



# dotnet install
# todo: remove this script and handle in ansible
- name: run dotnet installer
  script: msdotnetinst.sh
  args:
    chdir: /opt/cluster/mysrc/
    creates: /opt/dotnet/v200
  retries: 2
  register: dotnetinstsh
  tags: [dotnet]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [dotnet]
