title = "R-Pi Cluster: LanServices portal"
baseURL = "/"
buildDrafts = false
theme = "berrycluster"
copyright = "Nope"

[author]
    name = "crgm"
    email = "crgm@crgm.net"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Local blog for my Pi cluster."
  author = "crgm"
  debug_page_name = false

[[menu.main]]
    name = "status"
    pre = "<span class='nav-link'>"
    weight = -100
    url = "/status/"
[[menu.main]]
    name = "compute"
    pre = "<span class='nav-link'>"
    weight = -100
    url = "/compute/"
[[menu.main]]
    name = "about"
    pre = "<span class='nav-link'>"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "posts"
    pre = "<span class='nav-link'>"
    weight = -100
    url = "/post/"
