---
- debug: msg="test run of hello world "


# https://hub.docker.com/_/hello-world/


- name: pull hello world
  command: docker pull hello-world
  changed_when: false
  become: yes
  tags: [docker]


#- name: pull hello-world
#  docker_image:
#    name: _/hello-world


- name: run hello world
  command: docker run hello-world
  changed_when: false
  register: docker_hello_world
  become: yes
  failed_when:
    - "'installation appears to be working correctly' not in docker_hello_world.stdout"
  tags: [docker]