---
- debug: msg="Installing Docker container engine "
- debug: msg="enabled and started {{ rpi_docker_enabled }} "


# folder structure
- name: Create docker folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ docker_dir }}"
  become: yes
  tags: [docker]


- name: copy key
  copy:
    src: "docker.asc"
    dest: "/opt/cluster/docker/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  tags: [docker]


# copy docker scripts
- name: copy bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/docker/scripts/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ docker_script }}"
  tags: [docker]


- name: run docker install script
  script: install_docker.sh
  args:
    creates: /opt/cluster/docker/.dockerbin
    chdir: /opt/cluster/docker/scripts/
  become: yes
  tags: [docker]


- name: get docker version
  command: /usr/bin/docker --version
  register: docker_apt_version
  become: yes
  changed_when: false
  tags: [docker]


# Log version to ara
- name: docker version to ARA
  ara_record:
    key: "doker_version"
    type: "text"
    value: "{{ docker_apt_version.stdout }}"
  tags: [docker]


#-------------------------------------------------------------------------------

- name: docker enabled on boot
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: [docker]
  when: rpi_docker_enabled == true


#-------------------------------------------------------------------------------

# add user to docker group.
# Note: this gives them root on the host.
- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags: [docker]

# tools for managing docker containers/images
- import_tasks: manage_tools.yml
  tags: [docker]

#-------------------------------------------------------------------------------
# Test docker daemon is OK by running hello-world
# https://hub.docker.com/_/hello-world/

- name: pull hello world
  command: docker pull hello-world
  changed_when: false
  become: yes
  tags: [docker]

#- name: pull hello-world
#  docker_image:
#    name: _/hello-world

- name: run hello world
  command: docker run hello-world
  changed_when: false
  register: docker_hello_world
  become: yes
  failed_when:
    - "'installation appears to be working correctly' not in docker_hello_world.stdout"
  tags: [docker]

#-------------------------------------------------------------------------------

# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible docker roll ran
  tags: [docker]
  changed_when: false


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [docker]
