---
- debug: msg="Installing Docker container engine "

# Docs on Docker:
#
# https://github.com/OWASP/Docker-Security
# https://github.com/AonCyberLabs/Docker-Secure-Deployment-Guidelines


# Docker folder structure
- name: 'Create docker folders'
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: true
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ docker_dir }}"
  become: true
  tags: [docker]


- name: 'add entry to docker.list'
  copy:
    content: |
      # this file is ansible managed
      deb [arch=armhf] https://download.docker.com/linux/raspbian stretch test
    dest: "/etc/apt/sources.list.d/docker.list"
    mode: "0644"
    owner: "root"
    group: "root"
  become: true
  tags: [docker]


- name: "add docker key"
  apt_key:
    data: "{{ lookup('file', 'docker.asc') }}"
    state: present
  become: true
  tags: [docker]


- name: "update apt cache"
  apt:
    update_cache: true
  become: true
  changed_when: false
  tags: [docker]


- name: 'install docker from apt'
  apt:
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
    install_recommends: no
  become: true
  tags: [docker]


# get docker version
- name: get docker version
  command: /usr/bin/docker --version
  register: docker_apt_version
  become: true
  changed_when: false
  failed_when:
    - docker_apt_version.rc != 0
  tags: [docker]


#- name: use pip to install docker
#  pip:
#    name: docker-py
#    state: present
#    executable: pip3
#  become: true
#  tags: [docker]



- name: docker enabled on boot
  service:
    name: docker
    enabled: true
    state: started
  become: true
  tags: [docker]


# add user to docker group.
# Note: this gives them root on the host.
- name: add user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  tags: [docker]


# tools for managing docker containers/images
- import_tasks: manage_tools.yml
  tags: [docker]


# test docker - run hello world
- import_tasks: docker_hello_world.yml
  tags: [docker]


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible docker roll ran
  tags: [docker]
  changed_when: false


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [docker]
