---
- debug: msg="Installing Docker container engine "
- debug: msg="enabled and started {{ rpi_docker_enabled }} "

# For now all K8 and Docker setup is largely handled by bash scripts
# Docker installation is stable, nothing much changes.

# folder structure
- name: Create docker folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ docker_dir }}"
  become: yes
  tags: [docker]


- name: copy key
  copy:
    src: "docker.asc"
    dest: "/opt/cluster/docker/"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644
  tags: [docker]


# copy docker scripts to /opt/cluster/docker/scripts/
- name: copy bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/docker/scripts/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ docker_script }}"
  tags: [docker]


# install script
- name: run docker install script
  script: install_docker.sh
  args:
    creates: /opt/cluster/docker/docker-installed.txt
    chdir: /opt/cluster/docker/scripts/
  become: yes
  tags: [docker]


# get docker version
- name: get docker version
  command: /usr/bin/docker --version
  register: docker_apt_version
  become: yes
  changed_when: false
  failed_when:
    - docker_apt_version.rc != 0
  tags: [docker]


#- name: use pip to install docker
#  pip:
#    name: docker-py
#    state: present
#  become: yes
#  tags: [docker]



- name: docker enabled on boot
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: [docker]
  when: rpi_docker_enabled == true


# add user to docker group.
# Note: this gives them root on the host.
- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags: [docker]


# tools for managing docker containers/images
- import_tasks: manage_tools.yml
  tags: [docker]


- import_tasks: docker_hello_world.yml
  tags: [docker]


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible docker roll ran
  tags: [docker]
  changed_when: false


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [docker]
