---
- debug: msg="Installing Docker container engine "
- debug: msg="enabled and started {{ rpi_docker_enabled }} "


# folder structure
- name: Create docker folders
  file:
    path: "{{ item.dir }}"
    state: directory
    recurse: yes
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ docker_dir }}"
  become: yes
  tags: [docker]


# copy docker scripts
- name: copy bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/docker/scripts/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ docker_script }}"


# check for docker bin
- name: check for docker bin
  stat: path=/usr/bin/docker
  register: usrbin_docker
  tags: [docker]


# run docker-engine installer
- name: run installer
  shell: /opt/cluster/docker/scripts/getdocker.sh
  args:
    chdir: /opt/cluster/docker/scripts/
  when: usrbin_docker.stat.exists == False
  tags: [docker]
  register: rangetdocker


- name: pause
  pause:
    seconds: 10
  when: rangetdocker.changed
  tags: [docker]


# check package installed
- name: docker packages installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
       - docker-ce
  become: yes
  retries: 2
  tags: [docker]
  when: rangetdocker.changed


#-------------------------------------------------------------------------------

- name: docker enabled on boot
  service:
    name: docker
    enabled: yes
    state: started
  become: yes
  tags: [docker]
  when: rpi_docker_enabled == true


- name: pause after starting docker service
  pause:
    seconds: 20
  when: rangetdocker.changed


# disabled: STOP on boot
- name: docker stopped on boot
  service:
    name: docker
    enabled: no
    state: stopped
  become: yes
  tags: [docker]
  when: rpi_docker_enabled == false

- name: docker.socket stopped on boot
  service:
    name: docker.socket
    enabled: no
    state: stopped
  become: yes
  tags: [docker]
  when: rpi_docker_enabled == false


#-------------------------------------------------------------------------------

# add user to docker group. Note: this gives them root, for example:
#
# docker run -it --rm --privileged -v /:/mnt ubuntu bash
# echo 'ALL=(ALL) NOPASSWD:ALL' >> /mnt/etc/sudoers
#
- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags: [docker]

# tools for managing docker containers/images
- import_tasks: manage_tools.yml
  tags: [docker]

#-------------------------------------------------------------------------------
# Test docker daemon is OK by running hello-world
# https://hub.docker.com/_/hello-world/

- name: docker pull hello-world
  shell: docker pull hello-world
  changed_when: false
  become: yes

#- name: pull hello-world
#  docker_image:
#    name: _/hello-world

- name: test docker - run hello-world
  shell: docker run hello-world | grep "installation appears to be working correctly"
  changed_when: false
  register: docker_hello_world
  become: yes
  failed_when:
    - "'installation appears to be working correctly' not in docker_hello_world.stdout"

#-------------------------------------------------------------------------------

# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible docker roll ran
  tags: [docker]
  changed_when: false


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [docker]
