---
- debug: msg="docker manage_tools role "


# Docker garbage collection of containers and images
# https://github.com/spotify/docker-gc
- name: docker garbage collection tool
  git:
    repo: https://github.com/spotify/docker-gc.git
    dest: /opt/cluster/mysrc/docker-gc/
    update: no
  register: dockergc_clone
  tags:
    - skip_ansible_lint
