---
# Compute base


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  serial: 8
  roles:
    - ansible-pre-role


- name: Compute nodes main
  hosts: compute
  gather_facts: false
  max_fail_percentage: 49
  roles:
    - userac
    - base-system
    - hostsfile
    - ufw
    - rpilog
    - ssh-server
    - haveged
    - sysstat
    - ntp-client
    - distcc
    - mpich
    - golang
    - group-compute


- name: gather facts on nodes
  hosts: all
  gather_facts: True
  serial: 8
  roles:
    - ansible-post-role
