---
# Setup Rpi Deployer


- name: Deployer
  hosts: psi
  gather_facts: True
  roles:
    - ansible-pre-role
    - base-system
    - userac
    - rpilog
    - haveged
    - ntp-server
    - redis
    - nodejs
    - docker
    - group-deployer
    - host-psi
    - ssh-server
    - mpich
    - ansible-post-role
