---
# Compute base


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  serial: 10
  roles:
    - ansible-pre-role


- name: Compute nodes main
  hosts: compute
  gather_facts: false
  roles:
    - userac
    - base-system
    - hostsfile
    - rpilog
    - ssh-server
    - haveged
    - sysstat
    - ntp-client
    - distcc
    - mpich
    - golang
    - dotnet
    - hadoop
    - group-compute
    - docker


- name: gather facts on nodes
  hosts: all
  gather_facts: True
  roles:
    - ansible-post-role
