---
# LanServices main (Alpha and Beta)


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  roles:
    - ansible-pre-role


# do one server at a time (serial 1)
# stop the play if a task on a host fails
- name: LanServices Main (Alpha and Beta)
  hosts: lanservices
  gather_facts: false
  serial: 1
  any_errors_fatal: true
  roles:
    - userac
    - base-system
    - hostsfile
    - rpilog
    - ufw
    - ssh-server
    - haveged
    - uptimed
    - golang
    - ntp-server
    - ftp-server
    - dns-server
    - dhcp-server
    - dhcp-client
    - busybox-httpd
    - keepalived
    - group-lanservices


- name: gather facts on nodes
  hosts: all
  serial: 8
  gather_facts: True
  roles:
    - ansible-post-role
