---
# maintenance role Playbook


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  serial: 8
  roles:
    - ansible-pre-role


- name: LanServices Main (Alpha and Beta)
  hosts: lanservices
  gather_facts: false
  serial: 1
  max_fail_percentage: 49
  roles:
    - upgrades
    - reboot


- name: LanServices Misc (Omega)
  hosts: misc
  gather_facts: false
  serial: 1
  roles:
    - upgrades
    - reboot


- name: upgrades compute nodes two at a time
  hosts: compute
  gather_facts: false
  serial: 2
  max_fail_percentage: 49
  roles:
    - upgrades


- name: reboot compute nodes one by one
  hosts: compute
  gather_facts: false
  serial: 1
  roles:
    - reboot
