---
# LanServices main (Alpha and Beta)


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  roles:
    - ansible-pre-role


# do one server at a time (serial 1)
- name: LanServices Main (Alpha and Beta)
  hosts: lanservices
  gather_facts: false
  serial: 1
  roles:
    - userac
    - base-system
    - rpilog
    - ssh
    - haveged
    - uptimed
    - golang
    - ntp-server
    - dns-server
    - ftp-server
    - dhcp-client
    - dhcp-server
    - busybox-httpd
    - lanservices-node


- name: gather facts on nodes
  hosts: all
  gather_facts: True
  roles:
    - ansible-post-role
