---
# Compute webapp container hosting


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  serial: 8
  roles:
    - ansible-pre-role


- name: containers
  hosts: docker
  max_fail_percentage: 49
  gather_facts: false
  roles:
    - docker
    - kubernetes


- name: gather facts on nodes
  hosts: all
  serial: 8
  gather_facts: True
  roles:
    - ansible-post-role
