---
# LanServices main (Alpha and Beta)


- name: gather facts on other hosts
  hosts: all
  gather_facts: True
  roles:
    - ansible-pre-role


# do one server at a time (serial 1)
- name: LanServices Main (Alpha and Beta) part 1
  hosts: lanservices
  gather_facts: false
  serial: 1
  roles:
    - userac
    - base-system
    - hostsfile
    - rpilog
    - ssh-server
    - haveged
    - uptimed
    - golang
    - ntp-server
    - ftp-server


# need facts from all the other hosts for jina templates in dns playbook
- name: LanServices DNS
  hosts: all
  gather_facts: true
  serial: 1
  roles:
    - dns-server


- name: LanServices
  hosts: lanservices
  gather_facts: false
  serial: 1
  roles:
    - dhcp-server
    - dhcp-client
    - busybox-httpd
    - group-lanservices


- name: gather facts on nodes
  hosts: all
  gather_facts: True
  roles:
    - ansible-post-role
