---
#
# keepalived will ensure this shared IP address will be present
# in *at least* one place at any given time. There is no fencing or 'stonith'.
#
# http://www.keepalived.org/
# http://www.keepalived.org/doc/introduction.html

- debug: msg="Keepalived install "
- debug: msg="Floating IP is {{ rpi_loadbal_float_ip }} "


# install packages (if missing)
- name: install Keepalived programs
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - keepalived
  become: yes
  environment:
    # do not start Keepalived at the end of install
    RUNLEVEL: 1
  tags: [keepalived]


- name: keepalived conf
  template:
    src: primary.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    owner: root
    group: root
  notify: keepalived_reload
  become: yes
  tags: [keepalived]


# enabled on boot
- name: keepalived enabled on boot
  service:
    name: keepalived
    enabled: yes
    state: started
  become: yes
  register: keepalived_changed
  tags: [keepalived]


# pause
- name: wait a moment
  pause:
    seconds: 6
  when: keepalived_changed.changed
  changed_when: false
  tags: [keepalived]


# ping IP
- name: ping test floating IP
  command: ping -c 3 {{ rpi_loadbal_float_ip }}
  register: rpi_ping_float_ip
  changed_when: false
  tags: [keepalived]


# Log IP to ARA
- name: Log floating IP to ARA
  ara_record:
    key: "website"
    type: "url"
    value: "{{ rpi_loadbal_float_ip }}"
  tags: [keepalived]


# log
- name: notify rpicluster log
  command: logger -t rpicluster running Keepalived with floating IP {{ rpi_loadbal_float_ip }}
  changed_when: false
  tags: [keepalived]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [keepalived]
