---
- debug: msg="LanServices main cron jobs "


- name: add pathing to cron
  cron:
    name: PATH
    env: true
    value: /root/bin/
  become: true


- name: create cron daily script from template
  template:
    src: lansrvmain-cron-daily.j2
    dest: /root/crontab/lansrvmain-cron-daily.sh
    mode: 0755
    owner: root
    group: root
  become: true

- name: install daily cron script
  cron:
    name: "lansrvmain-cron-daily"
    special_time: "daily"
    job: "/root/crontab/lansrvmain-cron-daily.sh"
    state: "present"
    user: root
  become: true


- name: create cron hourly script from template
  template:
    src: lansrvmain-cron-hourly.j2
    dest: /root/crontab/lansrvmain-cron-hourly.sh
    mode: 0755
    owner: root
    group: root
  become: true

- name: install hourly cron script
  cron:
    name: "lansrvmain-cron-hourly"
    special_time: "hourly"
    job: "/root/crontab/lansrvmain-cron-hourly.sh"
    state: "present"
    user: root
  become: true
