---
- debug: msg="Lan Services main cron jobs "


- name: add pathing to cron
  cron:
    name: PATH
    env: yes
    value: /root/bin/
  become: yes


- name: copy cron daily script
  template:
    src: lansrvmain-cron-daily.j2
    dest: /root/crontab/lansrvmain-cron-daily
    mode: 0755
    owner: root
    group: root
  become: yes


- name: install daily cron script
  cron:
    name: "lansrv main daily"
    minute: "30"
    hour: "01"
    weekday: 7
    job: "/root/crontab/lansrvmain-cron-daily"
    user: root
  become: yes


- name: copy cron hourly script
  template:
    src: lansrvmain-cron-hourly.j2
    dest: /root/crontab/lansrvmain-cron-hourly
    mode: 0755
    owner: root
    group: root
  become: yes


- name: install hourly cron script
  cron:
    name: "lansrv main hourly"
    minute: "30"
    weekday: 7
    cron_file: "lansrvmain-cron-hourly"
    job: "/root/crontab/lansrvmain-cron-hourly"
    state: "present"
    user: root
  become: yes
