---
# Runs on LanServices main group - Alpha and Beta
- debug: msg="Lan Services role running "


- name: tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nmap
    - lynx
    - redir
    - proxychains
  become: yes
  retries: 2
  tags: [lanservices]


# custom systemd service "rpi-lanservices"
- import_tasks: systemd-cust.yml
  tags: [lanservices]


# security tasks for this group
- import_tasks: lanservices-security.yml


# cron scripts
- import_tasks: cron.yml
  tags: [lanservices]


- name: output to rpicluster log
  command: logger -t rpicluster ansible lanservices role ran
  changed_when: false
  tags: [lanservices]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: yes
  tags: [lanservices]
