---
# Nodes in the deploy group
- debug: msg="compute node tasks "
  tags: [computenode]


# java
- name: java
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates-java
    - openjdk-8-jdk
  become: yes
  retries: 2
  tags: [computenode]


# hardening tasks for this group
- import_tasks: compute-security.yml

# custom systemd service "rpi-compute"
- import_tasks: systemd-cust.yml


- name: output to rpicluster log
  command: logger -t rpicluster compute-node role ran
  changed_when: False
  tags: [computenode]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  tags: [computenode]
