---

# copy compute-boot.sh
- name: compute-boot script
  template:
    src: compute-boot.j2
    dest: /root/bin/compute-boot.sh
    validate: /bin/bash -n %s
    mode: 0770
    owner: root
    group: root
  become: true
  tags: [computenode]

# systemd script
- name: copy rpi compute systemd script
  copy:
    src: rpi-compute.service
    dest: /etc/systemd/system/rpi-compute.service
    mode: 0644
    owner: root
    group: root
  become: true
  changed_when: false
  notify:
    - systemctl-daemon-reload
    - restart-rpicompute
  tags: [computenode]

- name: enable rpi-compute systemd script
  systemd:
    name: rpi-compute
    enabled: true
    masked: no
  become: true
  tags: [computenode]
