---
# ftp server, used for network booting DHCP clients
- debug: msg="install ftpd "


- name: install ftpd
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tftp-hpa
    - tftpd-hpa
  become: true
  retries: 1
  tags: [ftpd]


- name: common ftp folders
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ common_ftp_dir }}"
  become: true
  tags: [ftpd]


- name: tftp config
  template:
    src: default.j2
    dest: /etc/default/tftpd-hpa
    owner: root
    group: root
    mode: 0664
    backup: true
  become: true
  notify: ftpd-restart
  tags: [ftpd]


- name: tftp welcome.txt
  template:
    src: welcome.j2
    dest: /srv/tftp/welcome.txt
    owner: root
    group: root
    mode: 0664
  become: true
  notify: ftpd-restart
  tags: [ftpd]


- name: tftpd hpa enabled on boot
  service:
    name: tftpd-hpa
    enabled: true
    state: started
  become: true
  tags: [ftpd]


- name: test ftp file download
  command: 
    cmd: "tftp -m binary  'localhost'  -c get 'welcome.txt'"
    chdir: "/tmp/"
  changed_when: false


# log
- name: notify rpicluster log
  command: logger -t rpicluster ansible installed tftpd
  changed_when: false
  tags: [ftpd]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  tags: [ftpd]
