---
# Tasks just for the Vagrant VM
# Get the VM environment setup with everything to setup the cluster.


- debug: msg="VagrantVM setup "
  tags: [vagrantvm]


# https://docs.ansible.com/ansible/latest/plugins/lookup/passwordstore.html
# this password is only used for verification of install - not senstive
- name: lookup test passwordstore password
  debug: msg="{{ lookup('passwordstore', 'test/test') }}"


- name: rpicluster syslog message
  syslogger:
    msg: "rpicluster: vagrantvm role running"
    priority: "notice"
    facility: "daemon"
    log_pid: true
  ignore_errors: True
  changed_when: False
  tags: [vagrantvm]


- name: set-chassis with hostnamectl
  command: hostnamectl set-chassis {{ rpi_racked }}
  become: yes
  changed_when: False
  tags: [vagrantvm]


# vagrant user member of adm group (to read /var/log/)
- name: add vagrant user to adm group
  user: name='vagrant'
    groups=adm
    append=yes
  become: yes
  tags: [vagrantvm]


# packages
- import_tasks: packages.yml
  tags: [vagrantvm,packages]


# apache
- import_tasks: apache.yml
  tags: [vagrantvm,apache]


# hugo
- import_tasks: hugo.yml
  tags: [vagrantvm,hugo]


# websocketd
- import_tasks: websocketd.yml
  tags: [vagrantvm,websocketd]


# golang
- import_tasks: golang.yml
  tags: [vagrantvm,golang]


# code
- import_tasks: code.yml
  tags: [vagrantvm,vagrantcode]


# lan scan script
- name: rpi_lan_nmap.sh
  template:
    src: rpi_lan_nmap.j2
    dest: /opt/cluster/bin/rpi_lan_nmap.sh
    mode: 0755
  tags: [vagrantvm]


# Log to ARA
- name: Compute sha256sum of file
  command: sha256sum ~/rpi_cluster/ansible/install-deploy-tools.sh
  register: bootstrap_deployer_sha256
  changed_when: false

- name: bootstrap deployer sha256
  ara_record:
    key: "sha256"
    value: "{{ bootstrap_deployer_sha256.stdout }}"


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{role_path|basename}}"
  become: yes
  tags: [vagrantvm]
