---
# NTP Client
- debug: msg="NTP Client "


# install
- name: ntp installed
  apt:
    name: ntp
    state: present
  become: true
  tags: [ntp]


# config file - Clients
- name: ntpd client conf
  template:
    src: ntp_client.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root
  become: true
  tags: [ntp]
  notify: ntp_restart


# started + enabled
- name: ntp started
  service:
    name: ntp
    state: started
    enabled: true
  become: true
  tags: [ntp]


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
  become: true
  tags: [ntp]
