---
# Deployer node packages
- debug: msg="deployer (dl_packages) "


- name: tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - pass
    - dh-make
    - devscripts
    - socat
    - lynx
    - nmap
    - toilet
    - emacs
    - ranger
    - mpich
    - maven
    - neofetch
    - proxychains
    - autossh
  become: true
  retries: 2


# R -  https://packages.debian.org/sid/r-recommended
#- name: install R language tools
#  apt: name={{ item }} state=present
#  become: true
#  loop:
#       - r-recommended
#       - r-cran-gplots
#       - r-cran-plotrix
#       - r-cran-tkrplot
#       - r-cran-vioplot
#       - rlplot
#  retries: 2
