---
# Deployer node packages
- debug: msg="deployer (dl_packages) "


- name: tools
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - pass
       - dh-make
       - devscripts
       - socat
       - lynx
       - nmap
       - telnet
       - toilet
       - emacs
       - ranger
       - mpich
       - maven
       - neofetch
  become: yes
  retries: 2


# R -  https://packages.debian.org/sid/r-recommended
#- name: install R language tools
#  apt: name={{ item }} state=present
#  become: yes
#  loop:
#       - r-recommended
#       - r-cran-gplots
#       - r-cran-plotrix
#       - r-cran-tkrplot
#       - r-cran-vioplot
#       - rlplot
#  retries: 2
