---
# Role for nodes in the Deployer group.

- debug: msg="deployer group role "


- name: check test password was set
  debug:
    msg: "{{ lookup('passwordstore', 'test/test') }}"


- name: create user deployops
  user:
    name: deployops
    groups: sshusers,staff,backup
    append: true
    shell: /bin/bash
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_file: .ssh/deployops_id_rsa
    createhome: true
    home: /home/deployops
  become: true
  tags: [deployer]


# Download src/pacakges etc
- import_tasks: dl_packages.yml
  tags: [deployer]


# scripts for deployer
- name: copy deployer bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/deploy-script/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
    force: no
  with_items: "{{ deployscript_binfile }}"
  tags: [deployer]


# custom systemd service "rpi-deployer"
- import_tasks: systemd-cust.yml


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible deployer role ran
  tags: [deployer]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: true
  changed_when: False
  tags: [deployer]
