---
# Playbook for the Deployer group.
- debug: msg="deployer role "


- name: Verify min ansible version requirements.
  assert:
    that: "ansible_version.full is version_compare('2.7', '>=')"
    msg: >
      "Upgrade ansible, this version is not supported"


- name: create user deployops
  user:
    name: deployops
    groups: sshusers,staff,backup
    append: yes
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/deployops_id_rsa
    createhome: yes
    home: /home/deployops
  become: yes


# Download src/pacakges etc
- import_tasks: dl_packages.yml
  tags: [deployer]


# scripts for deployer
- name: copy deployer bash scripts
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/deploy-script/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  with_items: "{{ deployscript_binfile }}"


# log
- name: output to rpicluster log
  command: logger -t rpicluster ansible deployer role ran
  tags: [deployer]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  changed_when: False
  tags: [deployer]
