---
# Run on the Deployers (The R-Pi "psi" & AdminVM)


- debug: msg="deployer role "


# Download src/pacakges etc
- import_tasks: dl_packages.yml
  tags: [deployer]


- name: copy bash scripts for deployer
  copy:
    src: "{{ item.file }}"
    dest: "/opt/cluster/bin/{{ item.file }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0750
  with_items: "{{ group_deployer_script }}"


# yarn
- import_tasks: yarn.yml
  tags:
    - deployer
    - yarn


# Firewall ---------------------------------------------------------------------

- name: copy deployer firewall script
  template:
    src: ufw.j2
    dest: /root/ufw.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  changed_when: False
  tags: [deployer]


- name: run firewall script
  shell: /root/ufw.sh
  args:
    chdir: /root/
    creates: /root/.ufw
  become: yes
  tags: [deployer]

# ------------------------------------------------------------------------------


# log
- name: output to rpicluster log
  shell: logger -t rpicluster ansible deployer role ran
  tags: [deployer]
  changed_when: False


- name: roles info txt
  lineinfile:
    path: /opt/cluster/data/info_roles.txt
    line: "{{ role_path|basename }}"
    owner: root
    group: root
    mode: 0444
  become: yes
  changed_when: False
  tags: [deployer]
