---
# Yarn - https://yarnpkg.com/en/
- debug: msg="deployer (yarn) "


# src folder
- name: create /opt/cluster/mysrc/yarn/
  file:
    path: /opt/cluster/mysrc/yarn/
    state: directory
    mode: 0755


# copy yarn gpg key to server also
- name: copy yarnpubkey
  copy:
    src: yarnkey.asc
    dest: /opt/cluster/mysrc/yarn/yarnkey.asc
    mode: 0644


# add apt gpg key
- name: Add yarn apt key
  apt_key:
    data: "{{ lookup('file', '/opt/cluster/mysrc/yarn/yarnkey.asc') }}"
    state: present
  become: yes


- name: add yarn apt repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  become: yes
  register: yarnaddapt


# update apt
- name: update apt cache
  apt:
    update_cache: yes
  become: yes
  retries: 1
  check_mode: no
  when: yarnaddapt.changed


# check package installed
- name: yarn packages installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
       - yarn
  become: yes
  retries: 1
