---
# no override for these vars


# Use the AARNet Mirror - https://mirror.aarnet.edu.au/about.html
apt_local_mirror: "http://mirror.aarnet.edu.au/pub/raspbian/raspbian"


# create folders (on every R-Pi)
common_dir: [
  { dir: '/opt/cluster/', mode: '0755', owner: "root", group: "root" },
  { dir: '/opt/cluster/data/', mode: '0755', owner: "root", group: "root" },
  { dir: '/opt/cluster/mysrc/', mode: '0700', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/opt/cluster/bin/', mode: '0755', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/home/{{ ansible_user_id }}/.config/htop/', mode: '0750', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/home/{{ ansible_user_id }}/tmp/', mode: '0750', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/home/{{ ansible_user_id }}/crontab/', mode: '0750', owner: "{{ ansible_user_id }}", group: "{{ ansible_user_id }}" },
  { dir: '/etc/ssh/auth_principals.d/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/etc/ansible/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/etc/ansible/facts.d/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/etc/rpicluster/', mode: '0700', owner: 'root', group: 'root' },
  { dir: '/root/rpicluster/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/root/bin/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/root/tmp/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/root/crontab/', mode: '0750', owner: 'root', group: 'root' },
  { dir: '/mnt/usbkey/', mode: '0755', owner: 'root', group: 'root' },
  { dir: '/mnt/sshfs/', mode: '0755', owner: 'root', group: 'root' }
]


# copy files
dotfiles: [
  {src: 'files/dotfiles/screenrc', dest: '~/.screenrc'},
  {src: 'files/dotfiles/htoprc', dest: '~/.config/htop/htoprc'},
  {src: 'files/dotfiles/vimrc', dest: '~/.vimrc'}
]


# copy ./files/bash-script/x to ~/bin/ on each host
binfile: [
  {file: 'fix_apt.sh'},
  {file: 'free_memcache.sh'},
  {file: 'led-blink.sh'},
  {file: 'disable-swap.sh'},
  {file: 'speedtest_100mbit.sh'},
  {file: 'check-syshealth.sh'},
  {file: 'rpi-temp-check.sh'},
  {file: 'default-sshd-login.sh'}
]


# remove these packages on all nodes
package_remove: [
  {rmapt: 'avahi-daemon'},
  {rmapt: 'triggerhappy'},
]


# /etc/sysctl.conf settings
sysctl_settings: [
  {name: 'net.ipv6.conf.all.disable_ipv6', value: '1', set: 'yes', state: 'present'},
  {name: 'net.ipv6.conf.default.disable_ipv6', value: '1', set: 'yes', state: 'present'},
  {name: 'kernel.randomize_va_space', value: '2', set: 'yes', state: 'present'},
  {name: 'net.core.rmem_max', value: '16777216', set: 'yes', state: 'present'},
  {name: 'net.core.wmem_max', value: '4194304', set: 'yes', state: 'present'},
  {name: 'net.ipv4.ip_local_port_range', value: '1024 65535', set: 'yes', state: 'present'},
  {name: 'net.ipv4.tcp_tw_reuse', value: '1', set: 'yes', state: 'present'}
]


# blacklist these kernel momdules
kern_blacklist_mod: [
  {name: 'snd_bcm2835'},
  {name: 'brcmfmac'},
  {name: 'brcmutil'},
  {name: 'cfg80211'},
  {name: 'bluetooth'}
]


# stop these system services
services_to_stop: [
  {name: 'avahi-daemon.socket'},
  {name: 'avahi-daemon.service'},
  {name: 'apt-daily.timer'},
  {name: 'apt-daily-upgrade.timer'},
  {name: 'apt-daily.service'},
  {name: 'apt-daily-upgrade.service'},
  {name: 'bluetooth.service'}
]
