---
# OpenSSH - https://www.openssh.com/
- debug: msg="ssh role "
  tags: [ssh]

- debug: msg="ssh port is {{ ssh_group_port }} "


- name: check ssh_group_port var is ok
  assert:
    that:
      - "{{ ssh_group_port }} >= 2000"
      - "{{ ssh_group_port }} <= 2999"
    fail_msg: " ssh_group_port must be between 2000 and 2999"


# message of the day (ssh login banner)
- name: MOTD
  template:
    src: etc/motd.j2
    dest: /etc/motd
  become: true
  tags: [ssh]


# SSH system wide Client config
- name: ssh client config file
  template:
    src: etc/ssh/ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  tags: [ssh]


# SSHD will only accept keys signed this key pair (excludes deployer)
# SSH CA key setup described at:
# https://code.facebook.com/posts/365787980419535/scalable-and-secure-access-with-ssh/

- name: upload ca.pub from deployer
  copy:
    src: ~/.ssh/my-ssh-ca/ca.pub
    dest: /etc/ssh/ca.pub
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  tags: [ssh]


# SSHD Server config
- name: sshd config file
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: sshd_restart
  become: true
  tags: [ssh]


#- name: ssh principals file
#  template:
#    src: auth_principals/pi.j2
#    dest: /etc/ssh/auth_principals.d/pi
#    owner: root
#    group: root
#    mode: 0644
#  become: true
#  tags: [ssh]