---
# OpenSSH - https://www.openssh.com/
- debug: msg="ssh role "
  tags: [ssh]


# message of the day (ssh login banner)
- name: MOTD
  template:
    src: motd.j2
    dest: /etc/motd
  become: yes
  tags: [ssh]


# SSH system wide Client config
- name: ssh client config file
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags: [ssh]


# SSHD will only accept keys signed this key pair (excludes deployer)
# SSH CA key setup described at:
# https://code.facebook.com/posts/365787980419535/scalable-and-secure-access-with-ssh/

- name: upload ca.pub
  copy:
    src: ~/.ssh/my-ssh-ca/ca.pub
    dest: /etc/ssh/ca.pub
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags: [ssh]


# SSHD Server config
- name: sshd config file
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: sshd_restart
  become: yes
  tags: [ssh]
